import { useState } from 'react'
import { boardTarget } from '../career/league'
import { clubs } from '../career/realData'
import { advanceDirectorCycle, buyDirectorPlayer, coachCandidates, directorPayroll, directorPlayer, directorRating, directorSquad, estimatedRank, hireCoach, promoteDirectorProspect, renewDirectorSeason, sellDirectorPlayer, squadAverage, structureCost, structureLabels, upgradeStructure, type DirectorCareer as DirectorCareerState, type DirectorStructure } from './directorModel'

type DirectorTab = 'home' | 'coach' | 'finance' | 'structure' | 'squad' | 'academy' | 'season'
const money = (value: number) => value >= 1000 ? `R$ ${(value / 1000).toFixed(1).replace('.', ',')} mi` : `R$ ${value} mil`
const clubName = (id: string) => clubs.find(club => club.id === id)?.name ?? 'Clube'
const resultLabel = { win: 'Vitória', draw: 'Empate', loss: 'Derrota' }
const styleLabel = { balanced: 'Equilibrado', attacking: 'Ofensivo', defensive: 'Defensivo', development: 'Formador' }

export function DirectorCareer({ career, onChange, onExit }: { career: DirectorCareerState; onChange: (career: DirectorCareerState) => void; onExit: () => void }) {
  const [tab, setTab] = useState<DirectorTab>('home')
  const [message, setMessage] = useState('')
  const club = clubs.find(item => item.id === career.clubId) ?? clubs[0]
  const rank = estimatedRank(career)
  const target = boardTarget(career.clubId)
  const payroll = directorPayroll(career)
  const squad = directorSquad(career)
  const last = career.cycles.at(-1)
  const dismissed = career.boardConfidence <= 10
  function apply(next: DirectorCareerState, success: string, failure: string) { if (next === career) return setMessage(failure); onChange(next); setMessage(success) }
  function advance() { const next = advanceDirectorCycle(career); apply(next, next.seasonComplete ? 'Temporada encerrada. O relatório anual está disponível.' : `Ciclo ${next.cycle} concluído.`, dismissed ? 'O conselho encerrou sua gestão.' : 'A temporada já foi encerrada.'); if (next.seasonComplete) setTab('season') }
  return <div className="office director-office"><aside className="sidebar director-sidebar"><div className="club-identity"><span className="crest" style={{ color: club.color, borderColor: club.color }}>{club.initials}</span><h2>{club.name}</h2><p>DIRIGENTE · {career.name}</p></div><nav aria-label="Área do dirigente">{([['home', '◫', 'Visão geral'], ['coach', '◇', 'Treinador'], ['finance', '$', 'Finanças'], ['structure', '⌂', 'Estrutura'], ['squad', '☷', 'Elenco'], ['academy', '△', 'Base'], ['season', '▥', 'Planejamento']] as const).map(([id, icon, label]) => <button key={id} className={tab === id ? 'nav-active' : ''} onClick={() => { setTab(id); setMessage('') }}><span aria-hidden="true">{icon}</span>{label}</button>)}</nav><div className="sidebar-foot"><span className={`badge ${dismissed ? '' : 'active'}`}>{dismissed ? 'GESTÃO ENCERRADA' : `CONSELHO · ${career.boardConfidence}`}</span><p>Temporada {career.season}<br />Ciclo {career.cycle}/10</p><button className="text-button" onClick={onExit}>← Seleção de carreira</button></div></aside>
    <main className="dashboard director-dashboard"><div className="dashboard-title"><div><p className="eyebrow">PRESIDÊNCIA / {club.name}</p><h1>{tab === 'home' ? `O futuro do clube passa por você.` : tab === 'coach' ? 'Escolha quem comanda o campo.' : tab === 'finance' ? 'Cada decisão precisa caber no projeto.' : tab === 'structure' ? 'Construa uma instituição mais forte.' : tab === 'squad' ? 'Planeje o elenco com responsabilidade.' : tab === 'academy' ? 'Prepare a próxima geração.' : 'Transforme temporadas em legado.'}</h1></div><span className="badge">T{career.season} · CICLO {career.cycle}/10</span></div>{message && <p className="market-message" role="status">{message}</p>}
      {dismissed && <section className="panel dismissal-panel"><p className="eyebrow">DECISÃO DO CONSELHO</p><h2>Sua gestão foi encerrada.</h2><p>A confiança chegou ao limite. O histórico permanece disponível para consulta.</p></section>}
      {tab === 'home' && <><section className="director-hero"><div><p className="eyebrow">PROJETO INSTITUCIONAL · TEMPORADA {career.season}</p><h2>Administre hoje.<br />Construa o amanhã.</h2><p>Equilibre desempenho esportivo, responsabilidade financeira, estrutura e formação de atletas.</p><button className="primary" disabled={career.seasonComplete || dismissed} onClick={advance}>{career.seasonComplete ? 'Temporada encerrada' : 'Avançar ciclo executivo'} →</button></div><div className="executive-score"><strong>{career.boardConfidence}</strong><span>CONFIANÇA DO CONSELHO</span><small>Meta esportiva: {target === 1 ? 'título' : `top ${target}`}</small></div></section><div className="season-stats director-numbers"><article><span>ORÇAMENTO</span><strong>{money(career.budget)}</strong><small>Saldo disponível</small></article><article><span>POSIÇÃO PROJETADA</span><strong>{rank}º</strong><small>{career.points} pontos</small></article><article><span>TORCIDA</span><strong>{career.supporterMood}%</strong><small>Humor atual</small></article><article><span>NÍVEL DO ELENCO</span><strong>{squadAverage(career)}</strong><small>{squad.length} atletas</small></article></div><div className="director-home-grid"><section className="panel"><p className="eyebrow">ÚLTIMO CICLO</p>{last ? <><h2>{club.initials} {last.goalsFor} × {last.goalsAgainst} {clubs.find(item => item.id === last.opponentId)?.initials}</h2><p>{resultLabel[last.result]} contra o {clubName(last.opponentId)}. A projeção atual é o {last.rank}º lugar.</p><small className="muted">Receitas {money(last.income)} · despesas {money(last.expenses)}</small></> : <><h2>O projeto começa agora.</h2><p>Revise treinador, orçamento e estrutura antes de avançar o primeiro ciclo.</p></>}</section><section className="panel"><p className="eyebrow">METAS DO CONSELHO</p><div className="director-goals"><p className={rank <= target ? 'done' : ''}>Terminar {target === 1 ? 'campeão' : `entre os ${target}`} <b>{rank <= target ? '✓' : `${rank}º`}</b></p><p className={career.budget >= 0 ? 'done' : ''}>Manter saldo positivo <b>{career.budget >= 0 ? '✓' : '!'}</b></p><p className={career.promoted > 0 ? 'done' : ''}>Promover um jovem <b>{career.promoted ? '✓' : '0/1'}</b></p></div></section><section className="panel"><p className="eyebrow">COMANDO TÉCNICO</p><h2>{career.coach.name}</h2><p>{styleLabel[career.coach.style]} · qualidade {career.coach.quality}</p><strong className="coach-confidence">Confiança {career.coachConfidence}/100</strong><button className="secondary" onClick={() => setTab('coach')}>Gerenciar treinador →</button></section></div></>}
      {tab === 'coach' && <section className="coach-center"><section className="coach-current"><div><p className="eyebrow">TREINADOR ATUAL</p><h2>{career.coach.name}</h2><p>{styleLabel[career.coach.style]} · qualidade {career.coach.quality} · salário {money(career.coach.salary)}/mês</p></div><div><strong>{career.coachConfidence}</strong><span>CONFIANÇA</span></div></section><section className="panel"><div className="section-heading"><div><p className="eyebrow">MERCADO DE TREINADORES</p><h2>Escolha o perfil do projeto</h2></div><span className="muted">A troca custa duas folhas salariais do novo treinador.</span></div><div className="coach-grid">{coachCandidates.map(coach => <article className={coach.id === career.coach.id ? 'current' : ''} key={coach.id}><small>{styleLabel[coach.style]}</small><h3>{coach.name}</h3><div><span>QUALIDADE</span><strong>{coach.quality}</strong></div><p>{money(coach.salary)}/mês</p><button className="primary" disabled={coach.id === career.coach.id || career.seasonComplete || dismissed} onClick={() => apply(hireCoach(career, coach.id), `${coach.name} é o novo treinador do ${club.name}.`, 'O orçamento não comporta a contratação ou este treinador já está no cargo.')}>{coach.id === career.coach.id ? 'No cargo' : 'Contratar'}</button></article>)}</div></section></section>}
      {tab === 'finance' && <section className="finance-center"><div className="season-stats"><article><span>SALDO ATUAL</span><strong>{money(career.budget)}</strong></article><article><span>RECEITAS NA TEMPORADA</span><strong>{money(career.revenue)}</strong></article><article><span>DESPESAS NA TEMPORADA</span><strong>{money(career.expenses)}</strong></article><article><span>FOLHA MENSAL</span><strong>{money(payroll)}</strong><small>Limite {money(career.wageLimit)}</small></article></div><section className="panel finance-ledger"><div className="section-heading"><div><p className="eyebrow">FLUXO FINANCEIRO</p><h2>Últimos ciclos</h2></div><span className="muted">Bilheteria, comercial, salários e operação.</span></div>{career.cycles.filter(item => item.season === career.season).slice().reverse().map(item => <article key={item.cycle}><span>C{item.cycle}</span><strong className="income">+ {money(item.income)}</strong><strong className="expense">− {money(item.expenses)}</strong><b>{money(item.balance)}</b></article>)}{career.cycle === 0 && <p className="muted">Avance o primeiro ciclo para registrar receitas e despesas.</p>}</section><details className="rules-explainer"><summary>Como o orçamento funciona?</summary><p>Cada ciclo gera bilheteria, receitas comerciais e bônus pelo resultado. A folha do elenco, treinador e manutenção das estruturas são descontadas automaticamente. Contratações e obras usam o saldo disponível.</p></details></section>}
      {tab === 'structure' && <section className="structure-center"><div className="structure-grid">{(Object.keys(structureLabels) as DirectorStructure[]).map(item => { const level = career.structures[item]; const cost = structureCost(career, item); return <article key={item}><div><span>{item === 'training' ? '⌂' : item === 'academy' ? '△' : item === 'medical' ? '+' : '◎'}</span><b>NÍVEL {level}/5</b></div><h2>{structureLabels[item].title}</h2><p>{structureLabels[item].description}</p><div className="structure-level">{Array.from({ length: 5 }, (_, index) => <i className={index < level ? 'active' : ''} key={index} />)}</div><button className="primary" disabled={level >= 5 || career.budget < cost || career.seasonComplete || dismissed} onClick={() => apply(upgradeStructure(career, item), `${structureLabels[item].title} avançou para o nível ${level + 1}.`, 'O nível máximo foi alcançado ou o orçamento é insuficiente.')}>{level >= 5 ? 'Nível máximo' : `Melhorar · ${money(cost)}`}</button></article> })}</div></section>}
      {tab === 'squad' && <section className="director-squad"><div className="season-stats"><article><span>ATLETAS</span><strong>{squad.length}/24</strong></article><article><span>NÍVEL MÉDIO</span><strong>{squadAverage(career)}</strong></article><article><span>FOLHA COM TREINADOR</span><strong>{money(payroll)}</strong></article><article><span>LIMITE DA FOLHA</span><strong>{money(career.wageLimit)}</strong></article></div><section className="panel"><div className="section-heading"><div><p className="eyebrow">JANELA DE TRANSFERÊNCIAS</p><h2>Atletas observados</h2></div><span className="muted">A rede melhora com o nível de observação.</span></div><div className="director-market-grid">{career.market.map(id => { const player = directorPlayer(id)!; return <article key={id}><div><span>{player.position}</span><strong>{player.rating}</strong></div><h3>{player.name}</h3><p>{clubName(player.clubId ?? '')}</p><small>{money(player.value)} · salário {money(player.wage)}</small><button className="primary" disabled={career.seasonComplete || dismissed} onClick={() => apply(buyDirectorPlayer(career, id), `${player.name} foi contratado.`, 'A contratação ultrapassa o orçamento, a folha ou o limite do elenco.')}>Contratar</button></article> })}</div></section><section className="panel director-roster"><div className="section-heading"><h2>Elenco profissional</h2><span className="muted">Venda disponível com no mínimo 17 atletas.</span></div><div className="table-wrap"><table><thead><tr><th>Atleta</th><th>Posição</th><th>Nível</th><th>Valor</th><th>Ação</th></tr></thead><tbody>{squad.map(player => <tr key={player.id}><td>{player.name}</td><td><span className="position">{player.position}</span></td><td><strong className="rating">{directorRating(career, player.id)}</strong></td><td>{money(player.value)}</td><td><button className="table-action danger" disabled={squad.length <= 16 || career.seasonComplete || dismissed} onClick={() => apply(sellDirectorPlayer(career, player.id), `${player.name} foi negociado.`, 'O elenco precisa manter pelo menos 16 atletas.')}>Vender</button></td></tr>)}</tbody></table></div></section></section>}
      {tab === 'academy' && <section className="director-academy"><section className="academy-director-hero"><div><p className="eyebrow">CATEGORIAS DE BASE · NÍVEL {career.structures.academy}</p><h2>Talento também é patrimônio.</h2><p>Invista na estrutura, acompanhe as promessas e abra espaço para quem vem de baixo.</p></div><strong>{career.promoted}</strong></section><div className="prospect-grid">{career.prospects.map(id => { const player = directorPlayer(id)!; const rating = Math.min(99, player.rating + Math.floor((career.structures.academy - 1) / 2)); return <article key={id}><div className="prospect-rating"><strong>{rating}</strong><span>{player.position}</span></div><h3>{player.name}</h3><p>{player.age} anos · potencial de desenvolvimento</p><small>Custo de promoção: R$ 300 mil</small><button className="primary" disabled={career.seasonComplete || dismissed || career.squad.length >= 24 || career.budget < 300} onClick={() => apply(promoteDirectorProspect(career, id), `${player.name} foi promovido ao profissional.`, 'O orçamento é insuficiente, o elenco está cheio ou a temporada foi encerrada.')}>Promover</button></article> })}</div>{!career.prospects.length && <p className="panel muted">As promessas observadas já receberam uma decisão nesta temporada.</p>}</section>}
      {tab === 'season' && <section className="director-planning">{career.seasonComplete ? <section className="season-board-report"><p className="eyebrow">RELATÓRIO ANUAL · TEMPORADA {career.season}</p><h2>{rank <= target && career.budget >= 0 ? 'Projeto aprovado pelo conselho.' : 'Uma temporada de ajustes.'}</h2><div className="season-stats"><article><span>POSIÇÃO</span><strong>{rank}º</strong><small>Meta: {target === 1 ? 'campeão' : `top ${target}`}</small></article><article><span>PONTOS</span><strong>{career.points}</strong></article><article><span>SALDO</span><strong>{money(career.budget)}</strong></article><article><span>JOVENS PROMOVIDOS</span><strong>{career.promoted}</strong></article></div><button className="primary" disabled={dismissed} onClick={() => apply(renewDirectorSeason(career), 'Nova temporada iniciada com aporte de patrocinadores.', 'O conselho encerrou sua gestão.')}>Iniciar temporada {career.season + 1} →</button></section> : <section className="panel"><p className="eyebrow">PLANEJAMENTO PLURIANUAL</p><h2>O legado é construído temporada após temporada.</h2><p>As estruturas, o elenco, o treinador e o saldo permanecem. Ao fechar cada ano, novos patrocínios entram e uma nova geração chega à base.</p><button className="secondary" onClick={() => setTab('home')}>Voltar à gestão →</button></section>}<section className="panel season-history"><div className="section-heading"><h2>Histórico da gestão</h2><span className="muted">Resultados preservados.</span></div>{career.seasons.slice().reverse().map(season => <article key={season.season}><span>T{season.season}</span><strong>{clubName(season.clubId)} · {season.rank}º lugar</strong><small>{season.points} pts · saldo {money(season.balance)} · conselho {season.boardConfidence} · {season.promoted} promovidos</small></article>)}{!career.seasons.length && <p className="muted">A primeira temporada ainda está em andamento.</p>}</section></section>}
      <p className="save-notice">Carreira de dirigente · salva neste navegador</p><footer className="prototype-note">MODO DIRIGENTE · Decisões esportivas e financeiras em ciclos executivos.</footer>
    </main></div>
}
