import { useEffect, useRef, useState } from 'react'
import { clubs, loadCareer, modes, saveCareer, squad, type Career, type Club } from '../features/career/model'

type View = 'modes' | 'setup' | 'office'
type Tab = 'overview' | 'squad' | 'tactics'
function Crest({ club }: { club: Club }) { return <span className="crest" style={{ color: club.color, borderColor: club.color }}>{club.initials}</span> }
function Pitch({ formation = '4-3-3' }: { formation?: string }) {
  const rows = formation.split('-').map(Number).reverse()
  return <div className="pitch" aria-label={`Campo com formação ${formation}`}><div className="center-circle" />{[...rows, 1].map((count, row) => <div className="pitch-row" key={row}>{Array.from({ length: count }, (_, i) => <span className="player-dot" key={i}>{row === rows.length ? '1' : rows.slice(0, row).reduce((sum, size) => sum + size, 0) + i + 2}</span>)}</div>)}</div>
}
export default function App() {
  const [career, setCareer] = useState<Career | null>(loadCareer)
  const [view, setView] = useState<View>('modes')
  const [tab, setTab] = useState<Tab>('overview')
  const [name, setName] = useState('')
  const [clubId, setClubId] = useState(clubs[0].id)
  const [notice, setNotice] = useState('')
  const heading = useRef<HTMLHeadingElement>(null)
  useEffect(() => { heading.current?.focus() }, [view, tab])
  const club = clubs.find(c => c.id === (view === 'office' ? career?.clubId : clubId)) ?? clubs[0]
  function update(next: Career) {
    setCareer(next)
    setNotice(saveCareer(next) ? 'Carreira salva neste navegador.' : 'Não foi possível salvar neste navegador. Seu progresso ficará apenas nesta sessão.')
  }
  return <div className="app-shell">
    <header className="topbar"><button className="brand" onClick={() => setView('modes')} aria-label="VT27 — início">VT<span>27</span><small>MODE CAREER</small></button><div className="top-meta"><span className="live-dot" /> PRÉ-TEMPORADA <span className="edition">EDIÇÃO 01</span></div></header>
    {view === 'modes' && <main className="selection">
      <div className="intro"><p className="eyebrow">SEU JOGO. SUA HISTÓRIA.</p><h1 tabIndex={-1} ref={heading}>O futebol tem muitos caminhos.<br /><em>Qual vai ser o seu?</em></h1><p>Três maneiras de viver o mesmo universo. Escolha de onde começa a sua história.</p></div>
      {career && <button className="resume" onClick={() => { setView('office'); setTab('overview') }}><span>CONTINUAR CARREIRA <strong>{career.name} · {clubs.find(c => c.id === career.clubId)?.name}</strong></span><span aria-hidden="true">↗</span></button>}
      <div className="mode-grid">{modes.map(mode => <article key={mode.id} className={`mode-card ${mode.available ? 'available' : ''}`}><div className="card-top"><span className="mode-number">{mode.number}</span><span className={mode.available ? 'badge active' : 'badge'}>{mode.available ? 'DISPONÍVEL · VERSÃO INICIAL' : 'EM DESENVOLVIMENTO'}</span></div><div className={`mode-art ${mode.id}`} aria-hidden="true">{mode.id === 'coach' ? <Pitch /> : <span className="giant-mark">{mode.id === 'player' ? '10' : 'FC'}</span>}</div><p className="eyebrow">{mode.subtitle}</p><h2>{mode.title}</h2><p>{mode.description}</p><button className={mode.available ? 'primary' : 'locked'} disabled={!mode.available} onClick={() => { setView('setup'); setNotice('') }}>{mode.available ? 'Começar como treinador' : 'Disponível em breve'}{mode.available && <span aria-hidden="true">↗</span>}</button></article>)}</div>
      <div className="selection-footer"><span>UM UNIVERSO. TRÊS PERSPECTIVAS.</span><span>Primeira etapa: sua chegada ao clube.</span></div>
    </main>}
    {view === 'setup' && <main className="setup"><button className="text-button" onClick={() => setView('modes')}>← Voltar aos modos</button><p className="eyebrow">CARREIRA DE TREINADOR / 01</p><h1 tabIndex={-1} ref={heading}>O banco de reservas<br /><em>espera por você.</em></h1><p className="muted">Defina seu perfil e escolha onde dar o primeiro passo.</p><form onSubmit={event => { event.preventDefault(); if (!name.trim()) return; update({ mode: 'coach', name: name.trim(), clubId, formation: '4-3-3' }); setTab('overview'); setView('office') }}>
      <label className="name-label" htmlFor="coach-name">Como devemos chamar você?</label><input id="coach-name" required maxLength={40} value={name} onChange={e => setName(e.target.value)} placeholder="Nome do treinador" autoComplete="given-name" pattern=".*\S.*" />
      <fieldset><legend>Escolha seu primeiro clube</legend><p className="muted">Clubes e elencos fictícios para explorar esta primeira versão.</p><div className="club-grid">{clubs.map(item => <label key={item.id} className={`club-option ${clubId === item.id ? 'selected' : ''}`}><div className="club-top"><Crest club={item} /><input type="radio" name="club" value={item.id} checked={clubId === item.id} onChange={() => setClubId(item.id)} /></div><h2>{item.name}</h2><span className="muted">{item.city}</span><p className="club-reputation">{item.reputation}</p><p>{item.description}</p><small>OBJETIVO DA DIRETORIA</small><strong>{item.objective}</strong></label>)}</div></fieldset>
      <div className="form-bottom"><p className="muted">{career ? 'Iniciar substituirá a carreira salva neste navegador.' : 'O progresso é salvo apenas neste navegador.'}</p><button className="primary" type="submit">Assumir o {club.name} <span aria-hidden="true">→</span></button></div></form></main>}
    {view === 'office' && career && <div className="office"><aside className="sidebar"><div className="club-identity"><Crest club={club} /><h2>{club.name}</h2><p>TREINADOR · {career.name}</p></div><nav aria-label="Área do treinador">{([['overview', '◫', 'Visão geral'], ['squad', '☷', 'Elenco'], ['tactics', '⌘', 'Prancheta']] as const).map(([id, icon, label]) => <button key={id} className={tab === id ? 'nav-active' : ''} onClick={() => setTab(id)}><span aria-hidden="true">{icon}</span>{label}</button>)}</nav><div className="sidebar-foot"><span className="badge active">TREINADOR</span><p>Jogador e dirigente<br />chegam nas próximas etapas.</p><button className="text-button" onClick={() => setView('modes')}>← Seleção de carreira</button></div></aside><main className="dashboard"><div className="dashboard-title"><div><p className="eyebrow">CENTRO DE COMANDO / {club.name}</p><h1 tabIndex={-1} ref={heading}>{tab === 'overview' ? `Bem-vindo, ${career.name}.` : tab === 'squad' ? 'Conheça seu elenco.' : 'Sua ideia de jogo.'}</h1></div><span className="badge">PRÉ-TEMPORADA · DIA 01</span></div>
      {tab === 'overview' && <><section className="welcome-panel"><div><p className="eyebrow">UM NOVO CAPÍTULO</p><h2>O próximo passo<br />começa no vestiário.</h2><p>A diretoria do {club.name} recebe você para um novo ciclo. Conheça os atletas e escolha sua formação inicial.</p><button className="primary" onClick={() => setTab('squad')}>Conhecer o elenco <span aria-hidden="true">→</span></button></div><div className="welcome-pitch"><Pitch formation={career.formation} /></div></section><div className="stat-grid"><article><p>ATLETAS NO PROTÓTIPO</p><strong>11 <small>jogadores</small></strong></article><article><p>FORMAÇÃO ATUAL</p><strong>{career.formation}</strong></article><article><p>FASE DA CARREIRA</p><strong>Preparação</strong></article></div><div className="lower-grid"><section className="panel"><p className="eyebrow">RECADO DA DIRETORIA</p><h2>Uma identidade para o clube.</h2><p>{club.objective}. Esse é o ponto de partida do seu trabalho no {club.name}.</p><span className="signature">A diretoria</span></section><section className="panel"><p className="eyebrow">SEUS PRIMEIROS PASSOS</p><button className="task-row" onClick={() => setTab('squad')}><span>01</span>Conhecer os jogadores <b>↗</b></button><button className="task-row" onClick={() => setTab('tactics')}><span>02</span>Definir a formação <b>↗</b></button><p className="muted">Treinos, calendário e partidas serão adicionados nas próximas versões.</p></section></div></>}
      {tab === 'squad' && <section className="panel"><div className="section-heading"><h2>Elenco inicial</h2><span className="muted">11 atletas · Dados demonstrativos</span></div><div className="table-wrap"><table><thead><tr><th scope="col">Jogador</th><th scope="col">Posição</th><th scope="col">Idade</th><th scope="col">Nível</th></tr></thead><tbody>{squad.map((player, i) => <tr key={player.name}><td><span className="shirt-number">{i + 1}</span>{player.name}</td><td><span className="position">{player.position}</span></td><td>{player.age}</td><td><strong className="rating">{player.rating}</strong></td></tr>)}</tbody></table></div><p className="muted">Este elenco de exemplo é compartilhado entre os clubes nesta etapa.</p></section>}
      {tab === 'tactics' && <section className="tactics-grid"><div className="panel"><p className="eyebrow">FORMAÇÃO BASE</p><h2>Como seu time ocupa o campo?</h2><p className="muted">Escolha a disposição inicial. Nesta versão, ela fica salva na carreira; ainda não influencia partidas.</p><fieldset className="formation-options"><legend>Esquema tático</legend>{['4-3-3', '4-4-2', '3-5-2'].map(value => <label key={value}><input type="radio" name="formation" checked={career.formation === value} onChange={() => update({ ...career, formation: value })} />{value}</label>)}</fieldset><p>A prancheta mostra posições ilustrativas. Escalação individual e instruções serão desenvolvidas na próxima etapa.</p></div><div className="tactics-pitch"><Pitch formation={career.formation} /></div></section>}
      <p className="save-notice" role="status">{notice || 'Carreira local · salva neste navegador'}</p><footer className="prototype-note">VERSÃO INICIAL · Clubes e atletas fictícios. Simulação de partidas ainda em desenvolvimento.</footer>
    </main></div>}
  </div>
}
