import { clubs } from '../career/realData'
import { playerPositions, type PlayerPosition } from './playerModel'

export function PlayerSetup({ name, clubId, position, number, replacing, onName, onClub, onPosition, onNumber, onBack, onStart }: { name: string; clubId: string; position: PlayerPosition; number: number; replacing: boolean; onName: (value: string) => void; onClub: (value: string) => void; onPosition: (value: PlayerPosition) => void; onNumber: (value: number) => void; onBack: () => void; onStart: () => void }) {
  const club = clubs.find(item => item.id === clubId) ?? clubs[0]
  return <main className="setup player-setup"><button className="text-button" onClick={onBack}>← Voltar aos modos</button><p className="eyebrow">CARREIRA DE JOGADOR / 02</p><h1>Seu nome na camisa.<br /><em>Sua história em campo.</em></h1><p className="muted">Crie o atleta, encontre sua posição e conquiste espaço no time.</p><form onSubmit={event => { event.preventDefault(); if (name.trim()) onStart() }}>
    <div className="player-identity-form"><label className="name-label" htmlFor="player-name">Nome do jogador<input id="player-name" required maxLength={40} value={name} onChange={event => onName(event.target.value)} placeholder="Nome do atleta" pattern=".*\S.*" /></label><label className="name-label" htmlFor="shirt-number">Número da camisa<input id="shirt-number" type="number" min="1" max="99" value={number} onChange={event => onNumber(Number(event.target.value))} /></label></div>
    <fieldset><legend>Qual é a sua posição?</legend><div className="position-choice-grid">{playerPositions.map(item => <label className={position === item.id ? 'selected' : ''} key={item.id}><input type="radio" name="position" checked={position === item.id} onChange={() => onPosition(item.id)} /><strong>{item.id}</strong><h2>{item.title}</h2><p>{item.description}</p></label>)}</div></fieldset>
    <fieldset><legend>Escolha o clube formador</legend><p className="muted">Você começa como promessa de 17 anos e precisa conquistar a confiança do treinador.</p><div className="club-grid compact-clubs">{clubs.map(item => <label key={item.id} className={`club-option ${clubId === item.id ? 'selected' : ''}`}><div className="club-top"><span className="crest" style={{ color: item.color, borderColor: item.color }}>{item.initials}</span><input type="radio" name="player-club" checked={clubId === item.id} onChange={() => onClub(item.id)} /></div><h2>{item.name}</h2><span className="muted">{item.city}</span></label>)}</div></fieldset>
    <div className="form-bottom"><p className="muted">{replacing ? 'Iniciar substituirá apenas a carreira de jogador salva.' : 'A carreira de treinador continuará salva separadamente.'}</p><button className="primary" type="submit">Assinar com o {club.name} →</button></div>
  </form></main>
}
