import { SeasonFinale } from '../career/SeasonFinale'
import { ProfessionalMarket } from '../career/EmploymentPanel'
import { useState } from 'react'
import { clubs, playersByClub } from '../career/realData'
import { externalCupClubs } from '../career/cupData'
import { acceptPlayerOffer, averageRating, improvePlayer, playerAttributeLabels, playerOverall, playerRole, playPlayerRound, stayUnderContract, trainPlayer, type MatchApproach, type PlayerAttribute, type PlayerCareer as PlayerCareerState, type PlayerTraining } from './playerModel'
import { nextPlayerFixture, playerSeasonLength } from './playerCompetition'
import { PlayerCompetitions } from './PlayerCompetitions'
import { PlayerLife } from './PlayerLife'

type PlayerTab = 'home' | 'competitions' | 'life' | 'training' | 'match' | 'development' | 'contract' | 'history'
const gameClubs = [...clubs, ...externalCupClubs]
const clubName = (id: string) => gameClubs.find(club => club.id === id)?.name ?? 'Clube'
const roleLabel = { starter: 'Titular', bench: 'Banco de reservas', out: 'Fora da lista' }
const approachText: Record<MatchApproach, { title: string; text: string }> = {
  safe: { title: 'Jogo simples', text: 'Proteja a posse, reduza riscos e cumpra sua função.' },
  team: { title: 'Jogar para o time', text: 'Procure assistências e participe da construção.' },
  bold: { title: 'Buscar protagonismo', text: 'Arrisque mais para tentar decidir a partida.' },
}
const trainingText: Record<PlayerTraining, { title: string; text: string }> = {
  physical: { title: 'Explosão e resistência', text: 'Trabalha velocidade e físico.' },
  finishing: { title: 'Finalização', text: 'Evolui chute e controle no último terço.' },
  creation: { title: 'Criação', text: 'Melhora passe, visão e condução.' },
  defensive: { title: 'Defesa', text: 'Treina marcação, duelos e força.' },
  recovery: { title: 'Recuperação', text: 'Recupere energia e moral sem sobrecarregar o corpo.' },
}

export function PlayerCareer({ career, onChange, onExit }: { career: PlayerCareerState; onChange: (career: PlayerCareerState) => void; onExit: () => void }) {
  const [tab, setTab] = useState<PlayerTab>('home')
  const [approach, setApproach] = useState<MatchApproach>('team')
  const [message, setMessage] = useState('')
  const [nextClub, setNextClub] = useState<string | null>(null)
  const club = clubs.find(item => item.id === career.clubId) ?? clubs[0]
  const overall = playerOverall(career)
  const role = playerRole(career)
  const last = career.matches.at(-1)
  const fixture = nextPlayerFixture(career)
  const opponent = gameClubs.find(item => item.id === fixture?.opponentId) ?? clubs[0]
  const compatiblePositions = career.position === 'PE' ? ['PE', 'PD'] : career.position === 'MC' ? ['MC', 'VOL'] : [career.position]
  const competition = (playersByClub[career.clubId] ?? []).filter(player => compatiblePositions.includes(player.position)).sort((a, b) => b.rating - a.rating).slice(0, 3)
  function apply(next: PlayerCareerState, success: string, failure: string) { if (next === career) return setMessage(failure); onChange(next); setMessage(success) }
  function play() { const next = playPlayerRound(career, approach); apply(next, next.seasonComplete ? 'Temporada encerrada. Suas propostas já chegaram.' : `${fixture?.competition === 'cup' ? 'Jogo da Copa' : `Rodada ${next.round}`} concluído.`, 'Este compromisso já foi encerrado.'); if (next.seasonComplete) setTab('history') }
  return <div className="office player-office"><aside className="sidebar player-sidebar"><div className="club-identity"><span className="crest" style={{ color: club.color, borderColor: club.color }}>{club.initials}</span><h2>{career.name}</h2><p>{club.name} · CAMISA {career.shirtNumber}</p></div><nav aria-label="Área do jogador">{([['home', '◫', 'Visão geral'], ['competitions', '▦', 'Competições'], ['life', '◇', 'Vestiário'], ['training', '△', 'Treinos'], ['match', '▷', 'Partida'], ['development', '↗', 'Evolução'], ['contract', '$', 'Contrato'], ['history', '▥', 'Carreira']] as const).map(([id, icon, label]) => <button key={id} className={tab === id ? 'nav-active' : ''} onClick={() => { setTab(id); setMessage('') }}><span aria-hidden="true">{icon}</span>{label}</button>)}</nav><div className="sidebar-foot"><span className="badge active">{career.position} · GER {overall}</span><p>{roleLabel[role]}<br />Confiança {career.trust}/100</p><button className="text-button" onClick={onExit}>← Seleção de carreira</button></div></aside>
    <main className="dashboard player-dashboard"><div className="dashboard-title"><div><p className="eyebrow">MODO JOGADOR / {club.name}</p><h1>{tab === 'home' ? `A bola está com você, ${career.name}.` : tab === 'competitions' ? 'A temporada inteira em suas mãos.' : tab === 'life' ? 'Sua carreira acontece dentro e fora do campo.' : tab === 'training' ? 'Todo treino deixa uma marca.' : tab === 'match' ? 'Faça a diferença em campo.' : tab === 'development' ? 'Construa o jogador que quer ser.' : tab === 'contract' ? 'Decida o próximo capítulo.' : 'Uma carreira escrita rodada a rodada.'}</h1></div><span className="badge">T{career.season} · RODADA {career.round}/{playerSeasonLength}</span></div>
      {message && <p className="market-message" role="status">{message}</p>}
      {tab === 'home' && <><section className="player-hero"><div><p className="eyebrow">CAMISA {career.shirtNumber} · {career.position}</p><h2>Da promessa<br />ao protagonismo.</h2><p>Treine, ganhe a confiança do treinador e transforme minutos em oportunidades.</p><button className="primary" onClick={() => setTab(career.seasonComplete ? 'contract' : 'training')}>{career.seasonComplete ? 'Ver propostas' : career.trainingCompleted ? 'Ir para a partida' : 'Começar treino'} →</button></div><div className="player-card-visual"><span>{career.shirtNumber}</span><strong>{career.name}</strong><small>{club.initials} · GER {overall}</small></div></section><div className="season-stats player-numbers"><article><span>STATUS NO ELENCO</span><strong>{roleLabel[role]}</strong><small>Confiança {career.trust}/100</small></article><article><span>ENERGIA</span><strong>{career.energy}%</strong><small>Forma {career.dynamics.form} · moral {career.dynamics.morale}</small></article><article><span>PARTICIPAÇÕES EM GOLS</span><strong>{career.stats.goals + career.stats.assists}</strong><small>{career.stats.goals} gols · {career.stats.assists} assist.</small></article><article><span>NOTA MÉDIA</span><strong>{averageRating(career.stats).toFixed(1)}</strong><small>{career.stats.appearances} jogos</small></article></div><div className="lower-grid"><section className="panel"><p className="eyebrow">PRÓXIMO COMPROMISSO</p><h2>{career.seasonComplete ? 'Temporada concluída' : fixture?.atHome ? `${club.name} × ${opponent.name}` : `${opponent.name} × ${club.name}`}</h2><p>{career.seasonComplete ? 'Analise as propostas e escolha onde jogará na próxima temporada.' : `Sua situação atual: ${roleLabel[role].toLowerCase()}. Treinar melhora ritmo e confiança antes da rodada.`}</p><button className="secondary" onClick={() => setTab(career.seasonComplete ? 'contract' : 'match')}>{career.seasonComplete ? 'Abrir mercado' : 'Preparar partida'} →</button></section><section className="panel"><p className="eyebrow">OBJETIVOS PESSOAIS</p><div className="player-objectives"><p className={career.trust >= 60 ? 'done' : ''}>Chegar a 60 de confiança <b>{career.trust >= 60 ? '✓' : `${career.trust}/60`}</b></p><p className={career.stats.appearances >= 25 ? 'done' : ''}>Participar de 25 jogos <b>{career.stats.appearances}/25</b></p><p className={career.stats.goals + career.stats.assists >= 5 ? 'done' : ''}>Somar 5 participações em gols <b>{career.stats.goals + career.stats.assists}/5</b></p></div></section></div></>}
      {tab === 'competitions' && <PlayerCompetitions career={career} />}
      {tab === 'life' && <PlayerLife career={career} onChange={onChange} />}
      {tab === 'training' && <section className="player-training"><div className="player-section-lead"><div><p className="eyebrow">SEMANA DE PREPARAÇÃO</p><h2>{career.trainingCompleted ? 'Treino concluído.' : 'Escolha seu foco.'}</h2><p>Cada rodada permite uma sessão. O treino consome energia, aumenta o ritmo e aproxima você da titularidade.</p></div><div><strong>{career.energy}%</strong><span>ENERGIA</span></div></div><div className="player-training-grid">{(Object.keys(trainingText) as PlayerTraining[]).map(kind => <article key={kind}><span>{kind === 'physical' ? '⚡' : kind === 'finishing' ? '◎' : kind === 'creation' ? '◇' : '◆'}</span><h3>{trainingText[kind].title}</h3><p>{trainingText[kind].text}</p><button className="primary" disabled={career.trainingCompleted || career.seasonComplete} onClick={() => apply(trainPlayer(career, kind), 'Treino concluído. Ritmo e confiança aumentaram.', 'Você já treinou nesta rodada ou precisa recuperar energia.')}>{career.trainingCompleted ? 'Sessão encerrada' : 'Realizar treino'}</button></article>)}</div><section className="panel player-competition"><div className="section-heading"><div><p className="eyebrow">DISPUTA POR POSIÇÃO</p><h2>Concorrentes no elenco real</h2></div><span className="muted">Sua confiança define o espaço conquistado.</span></div>{competition.map(player => <div key={player.id}><span>{player.position}</span><strong>{player.name}</strong><b>{player.rating}</b></div>)}</section><details className="rules-explainer"><summary>Como conquisto a titularidade?</summary><p>A comissão considera confiança, energia e rendimento. A partir de 60 de confiança, com pelo menos 50% de energia, você começa como titular. Entre 28 e 59, inicia no banco e pode entrar durante a partida.</p></details></section>}
      {tab === 'match' && <section className="player-match-center"><div className="player-match-banner"><div><small>{career.seasonComplete ? 'TEMPORADA ENCERRADA' : `RODADA ${career.round + 1}`}</small><strong>{club.initials}</strong><span>×</span><strong>{career.seasonComplete ? 'FIM' : opponent.initials}</strong></div><p>{career.seasonComplete ? 'Mercado de transferências aberto' : `${fixture?.atHome ? club.name : opponent.name} contra ${fixture?.atHome ? opponent.name : club.name}`}</p></div>{career.seasonComplete ? <section className="panel season-complete"><h2>Temporada encerrada</h2><p>Seu desempenho despertou interesse no mercado. Abra a área Contrato para decidir o futuro.</p><button className="primary" onClick={() => setTab('contract')}>Ver propostas →</button></section> : <><div className="season-stats player-match-status"><article><span>ESCALAÇÃO</span><strong>{roleLabel[role]}</strong></article><article><span>ENERGIA</span><strong>{career.energy}%</strong></article><article><span>RITMO</span><strong>{career.sharpness}</strong></article><article><span>CONFIANÇA</span><strong>{career.trust}</strong></article></div><section className="panel"><div className="section-heading"><div><p className="eyebrow">PLANO PESSOAL</p><h2>Como você entrará em campo?</h2></div><span className="muted">A escolha muda risco, nota, gols e assistências.</span></div><div className="approach-grid">{(Object.keys(approachText) as MatchApproach[]).map(item => <button className={approach === item ? 'chosen' : ''} key={item} onClick={() => setApproach(item)}><strong>{approachText[item].title}</strong><span>{approachText[item].text}</span></button>)}</div><div className="player-objectives"><p><span>META DA PARTIDA</span> <b>{career.dynamics.objective.title}</b></p></div><button className="primary play-player-match" onClick={() => career.dynamics.pendingDecision ? setTab('life') : play()}>{career.dynamics.pendingDecision ? 'Resolva a decisão no Vestiário' : 'Jogar compromisso →'}</button></section></>}{last && <section className="panel player-last-match"><div className="section-heading"><div><p className="eyebrow">ÚLTIMA ATUAÇÃO</p><h2>{clubs.find(item => item.id === last.clubId)?.initials} {last.teamGoals} × {last.opponentGoals} {clubs.find(item => item.id === last.opponentId)?.initials}</h2></div><strong className="player-rating-big">{last.rating ? last.rating.toFixed(1) : '—'}</strong></div><div className="season-stats"><article><span>FUNÇÃO</span><strong>{roleLabel[last.role]}</strong></article><article><span>MINUTOS</span><strong>{last.minutes}</strong></article><article><span>GOLS</span><strong>{last.goals}</strong></article><article><span>ASSISTÊNCIAS</span><strong>{last.assists}</strong></article></div></section>}</section>}
      {tab === 'development' && <section className="player-development"><div className="player-section-lead"><div><p className="eyebrow">CENTRO DE EVOLUÇÃO</p><h2>Nível geral {overall}</h2><p>Boas atuações geram experiência. A cada 100 pontos, você recebe um ponto para aplicar no atributo que escolher.</p></div><div><strong>{career.skillPoints}</strong><span>PONTOS LIVRES</span></div></div><div className="attribute-grid">{(Object.keys(playerAttributeLabels) as PlayerAttribute[]).map(attribute => <article key={attribute}><div><span>{playerAttributeLabels[attribute]}</span><strong>{career.attributes[attribute]}</strong></div><div className="attribute-track"><span style={{ width: `${career.attributes[attribute]}%` }} /></div><button aria-label={`Evoluir ${playerAttributeLabels[attribute]}`} disabled={!career.skillPoints || career.attributes[attribute] >= 99} onClick={() => apply(improvePlayer(career, attribute), `${playerAttributeLabels[attribute]} evoluiu.`, 'Você precisa conquistar um ponto de evolução.')}>+</button></article>)}</div><section className="panel experience-panel"><div><span>EXPERIÊNCIA ATUAL</span><strong>{career.experience}/100</strong></div><div className="attribute-track"><span style={{ width: `${career.experience}%` }} /></div></section></section>}
      {tab === 'contract' && <ProfessionalMarket career={career} onChange={onChange} />}
      {tab === 'contract' && <section className="player-contract">{nextClub && career.seasonComplete && <section className="panel renewal-confirm"><h2>Iniciar temporada {career.season + 1}?</h2><p>Destino: {nextClub === 'stay' ? club.name : clubName(nextClub)}. Seus resultados serão arquivados; a nova campanha começa com calendário e números da temporada zerados. A evolução e o histórico da carreira continuam.</p><button className="secondary" onClick={() => setNextClub(null)}>Rever decisão</button><button className="primary" onClick={() => { apply(nextClub === 'stay' ? stayUnderContract(career) : acceptPlayerOffer(career, nextClub), 'Nova temporada iniciada. Seu histórico foi preservado.', 'Esta proposta não está mais disponível.'); setNextClub(null); setTab('home') }}>Confirmar próxima temporada</button></section>}<section className="player-contract-card"><span className="crest" style={{ color: club.color, borderColor: club.color }}>{club.initials}</span><div><p className="eyebrow">CONTRATO ATUAL</p><h2>{club.name}</h2><p>{career.contract.seasons} temporadas · R$ {career.contract.wage} mil/mês</p></div><strong>{roleLabel[role]}</strong></section>{career.seasonComplete ? <section className="panel"><div className="section-heading"><div><p className="eyebrow">JANELA DE DECISÃO</p><h2>Escolha seu próximo capítulo</h2></div><span className="muted">A escolha inicia imediatamente a nova temporada.</span></div><div className="player-offer-grid">{career.offers.map(offer => { const offeredClub = clubs.find(item => item.id === offer.clubId)!; return <article key={offer.clubId}><span className="crest" style={{ color: offeredClub.color, borderColor: offeredClub.color }}>{offeredClub.initials}</span><h3>{offeredClub.name}</h3><p>{offer.role}</p><strong>R$ {offer.wage} mil/mês</strong><small>{offer.seasons} temporadas</small><button className="primary" onClick={() => setNextClub(offer.clubId)}>{offer.clubId === career.clubId ? 'Renovar contrato' : 'Aceitar transferência'}</button></article> })}</div>{career.contract.seasons > 1 && <button className="secondary stay-button" onClick={() => setNextClub('stay')}>Cumprir o contrato atual sem renovar</button>}</section> : <section className="panel contract-wait"><h2>Seu futuro é decidido em campo.</h2><p>Ao final das 38 rodadas e da Copa, o clube atual e outros projetos apresentarão propostas de contrato. Nível geral, nota média e participações em gols influenciam o mercado.</p><div className="season-stats"><article><span>RODADAS RESTANTES</span><strong>{playerSeasonLength - career.round}</strong></article><article><span>NOTA MÉDIA</span><strong>{averageRating(career.stats).toFixed(1)}</strong></article><article><span>NÍVEL GERAL</span><strong>{overall}</strong></article><article><span>VÍNCULO</span><strong>{career.contract.seasons}T</strong></article></div></section>}</section>}
      {tab === 'history' && <section className="player-history"><SeasonFinale career={career} />{career.seasonComplete && <button className="primary" onClick={() => setTab('contract')}>Escolher o próximo capítulo →</button>}<div className="season-stats"><article><span>JOGOS NA CARREIRA</span><strong>{career.allTime.appearances + career.stats.appearances}</strong></article><article><span>GOLS</span><strong>{career.allTime.goals + career.stats.goals}</strong></article><article><span>ASSISTÊNCIAS</span><strong>{career.allTime.assists + career.stats.assists}</strong></article><article><span>MELHOR EM CAMPO</span><strong>{career.allTime.motm + career.stats.motm}</strong></article></div><section className="panel"><div className="section-heading"><div><p className="eyebrow">LINHA DO TEMPO</p><h2>Temporadas</h2></div><span className="muted">Todo o caminho fica registrado.</span></div><article className="player-season-row current"><span>T{career.season}</span><div><strong>{club.name}</strong><small>{career.seasonComplete ? 'Encerrada' : 'Em andamento'} · nível {overall}</small></div><b>{career.stats.goals}G · {career.stats.assists}A</b></article>{career.seasons.slice().reverse().map(season => <article className="player-season-row" key={season.season}><span>T{season.season}</span><div><strong>{clubName(season.clubId)}</strong><small>{season.stats.appearances} jogos · nota {averageRating(season.stats).toFixed(1)} · nível {season.overall}</small></div><b>{season.stats.goals}G · {season.stats.assists}A</b></article>)}</section></section>}
      <p className="save-notice">Carreira de jogador · salva neste navegador</p><footer className="prototype-note">MODO JOGADOR · 38 rodadas, Copa nacional e evolução coletiva em uma temporada completa.</footer>
    </main></div>
}
