import { clubs } from '../career/realData'
import { externalCupClubs } from '../career/cupData'
import { playerCupStatus, playerSeasonLength, playerStandings } from './playerCompetition'
import type { PlayerCareer } from './playerModel'

const clubName = (id: string) => [...clubs, ...externalCupClubs].find(club => club.id === id)?.name ?? 'Clube'

export function PlayerCompetitions({ career }: { career: PlayerCareer }) {
  const table = playerStandings(career.leagueResults), own = table.find(row => row.id === career.clubId)!, rank = table.findIndex(row => row.id === career.clubId) + 1
  return <section className="player-competitions"><div className="league-summary"><article><span>BRASILEIRÃO</span><strong>{career.round ? `${rank}º lugar` : 'A começar'}</strong><small>{own.points} pontos · {career.round}/{playerSeasonLength} jogos</small></article><article><span>COPA NACIONAL</span><strong>{playerCupStatus(career.cup, career.clubId)}</strong><small>{career.matches.filter(match => match.competition === 'cup').length} partidas disputadas</small></article><article><span>EVOLUÇÃO DO TIME</span><strong>{own.goalsFor} GP · {own.goalsAgainst} GC</strong><small>{own.wins} vitórias · {own.draws} empates · {own.losses} derrotas</small></article></div><section className="panel"><div className="section-heading"><div><p className="eyebrow">CLASSIFICAÇÃO AO VIVO</p><h2>Brasileirão · Temporada {career.season}</h2></div><span className="muted">Todos os clubes jogam a cada rodada.</span></div><div className="table-wrap"><table><thead><tr><th>#</th><th>Clube</th><th>J</th><th>V</th><th>SG</th><th>PTS</th></tr></thead><tbody>{table.map((row, index) => <tr className={row.id === career.clubId ? 'current-club-row' : ''} key={row.id}><td>{index + 1}</td><th>{row.name}</th><td>{row.played}</td><td>{row.wins}</td><td>{row.difference}</td><td><strong>{row.points}</strong></td></tr>)}</tbody></table></div></section><section className="panel"><div className="section-heading"><div><p className="eyebrow">TRAJETÓRIA COLETIVA</p><h2>Últimos compromissos</h2></div><span className="muted">Liga e Copa reunidas.</span></div><div className="world-feed">{career.matches.slice(-8).reverse().map((match, index) => <article key={`${match.season}-${match.competition}-${match.round}-${index}`}><span>{match.competition === 'cup' ? 'COPA' : `R${match.round}`}</span><div><strong>{clubName(match.clubId)} {match.teamGoals} × {match.opponentGoals} {clubName(match.opponentId)}</strong><small>{match.atHome ? 'Em casa' : 'Fora'} · {match.minutes ? `Nota ${match.rating.toFixed(1)}` : 'Não relacionado'}</small></div><b>{match.teamGoals > match.opponentGoals ? 'VITÓRIA' : match.teamGoals === match.opponentGoals ? 'EMPATE' : 'DERROTA'}</b></article>)}</div></section></section>
}
