import { allClubs, type Career } from './model'
import { cupFixture, cupOf, tieWinner } from './cup'
import { cupSchedule, cupStageNames } from './cupData'
import type { CupStage } from './types'

const stages = [5, 6, 7, 8, 9] as CupStage[]
const clubName = (id?: string) => allClubs.find(club => club.id === id)?.name ?? id ?? 'A definir'
export function CupPanel({ career, onMatch, onSchedule }: { career: Career; onMatch: () => void; onSchedule: () => void }) {
  if (!career.leagueActive) return <section className="panel cup-waiting"><p className="eyebrow">COPA DO BRASIL</p><h2>Sua vaga começa com a temporada oficial.</h2><p>Conclua a pré-temporada e inicie o Brasileirão. Os 20 clubes da Série A entram diretamente na 5ª fase da copa.</p><button className="primary" onClick={onSchedule}>Ir ao calendário →</button></section>
  const cup = cupOf(career)
  const fixture = cupFixture(career)
  const ownTie = cup.ties.find(tie => [tie.home, tie.away].includes(career.clubId))
  const currentWinner = ownTie ? tieWinner(ownTie, cup.results) : undefined
  const resultText = cup.champion ? cup.champion === career.clubId ? 'CAMPEÃO' : `CAMPEÃO: ${clubName(cup.champion)}` : cup.eliminated ? 'ELIMINADO' : 'NA DISPUTA'
  return <section className="cup-hub"><div className="cup-hero"><div><p className="eyebrow">COPA DO BRASIL · TEMPORADA {career.seasonNumber ?? 1}</p><h2>Cada confronto vale uma história.</h2><p>Trinta e dois clubes reais, mata-mata nacional e uma decisão em jogo único.</p></div><div className="cup-mark" aria-hidden="true">CDB</div></div>
    <div className="league-summary"><article><span>SITUAÇÃO</span><strong>{resultText}</strong><small>{cup.champion ? 'Competição encerrada' : cupStageNames[cup.stage]}</small></article><article><span>PREMIAÇÃO ACUMULADA</span><strong>R$ {cup.prize.toLocaleString('pt-BR')} mil</strong><small>Adicionada ao orçamento ao avançar</small></article><article><span>PRÓXIMA DATA</span><strong>{fixture ? `Dia ${career.day}` : cup.eliminated || cup.champion ? '—' : `Dia ${cupSchedule[cup.stage].find(day => day >= (career.day ?? 1)) ?? '—'}`}</strong><small>{fixture ? `${fixture.atHome ? 'Em casa' : 'Fora'} · contra ${clubName(fixture.opponent)}` : 'Consulte o calendário'}</small></article></div>
    {fixture && <section className="next-day cup-callout"><div><p className="eyebrow">DIA DE COPA · {cupStageNames[fixture.stage]}</p><h2>{fixture.leg === 2 ? 'A vaga será decidida agora.' : fixture.stage === 9 ? 'Noventa minutos pelo título.' : 'Começa um novo confronto.'}</h2><p>{clubName(fixture.home)} × {clubName(fixture.away)}</p></div><button className="primary" onClick={onMatch}>{career.match ? 'Abrir partida' : 'Preparar confronto'} →</button></section>}
    <section className="panel"><div className="section-heading"><h2>Chaveamento</h2><span className="muted">O caminho é definido a cada temporada</span></div><div className="cup-stage-tabs">{stages.map(stage => <div className={stage === cup.stage ? 'cup-stage current' : 'cup-stage'} key={stage}><small>{cupStageNames[stage]}</small><strong>{stage === 9 ? 2 : 2 ** (10 - stage)} clubes</strong></div>)}</div><div className="tie-grid">{cup.ties.map((tie, index) => { const first = cup.results.find(result => result.stage === tie.stage && result.home === tie.home && result.away === tie.away); const second = cup.results.find(result => result.stage === tie.stage && result.home === tie.away && result.away === tie.home); const winner = tieWinner(tie, cup.results); return <article className={[tie.home, tie.away].includes(career.clubId) ? 'cup-tie own' : 'cup-tie'} key={tie.home + tie.away}><small>CONFRONTO {String(index + 1).padStart(2, '0')}</small><div><span>{clubName(tie.home)}</span><strong>{first ? first.homeGoals : '·'}{second ? ` + ${second.awayGoals}` : ''}</strong></div><div><span>{clubName(tie.away)}</span><strong>{first ? first.awayGoals : '·'}{second ? ` + ${second.homeGoals}` : ''}</strong></div>{winner && <p>Classificado: <b>{clubName(winner)}</b>{second?.penaltiesWinner ? ' nos pênaltis' : ''}</p>}</article> })}</div>{!cup.ties.length && <p className="muted">O chaveamento desta temporada foi encerrado.</p>}{ownTie && !currentWinner && <p className="cup-own-note">Seu confronto atual está destacado.</p>}</section>
    <details className="rules-explainer"><summary>Como funciona esta Copa do Brasil?</summary><p>Os 20 participantes da Série A e 12 classificados de outras divisões formam a 5ª fase. Da 5ª fase até a semifinal, cada confronto tem ida e volta; empate no placar agregado vai para os pênaltis. A final é disputada em partida única. Os adversários e o chaveamento mudam a cada temporada.</p><p>As premiações e probabilidades são parâmetros internos do simulador.</p></details>
  </section>
}
