import { PlayerDossier } from './PlayerDossier'
import { useState } from 'react'
import { clubs } from './realData'
import { employmentOf, marketProfessionals, offerEmployment, openEmployment, ownEmployment, signEmployment, withdrawEmployment, type MarketCareer } from './professionalMarket'
import type { EmploymentDeal, EmploymentTerms } from './employment'
import { acceptPlayerOffer, counterPlayerOffer, playerMarketValue, rejectPlayerOffer, stayUnderContract, type PlayerCareer } from '../player/playerModel'

const money = (value: number) => `R$ ${value.toLocaleString('pt-BR')} mil`
const clubName = (id: string) => clubs.find(club => club.id === id)?.name ?? 'Sem clube'
export function ProfessionalMarket<T extends MarketCareer>({ career, onChange }: { career: T; onChange: (next: T) => void }) {
  const [search, setSearch] = useState(''), [kind, setKind] = useState('self'), [destination, setDestination] = useState(clubs.find(club => club.id !== career.clubId)!.id as string)
  const state = employmentOf(career), contract = ownEmployment(career), people = marketProfessionals(career).filter(person => person.kind === kind && person.name.toLocaleLowerCase('pt-BR').includes(search.toLocaleLowerCase('pt-BR')))
  if (career.mode === 'player') return <PlayerOfferInbox career={career} onChange={onChange as (next: PlayerCareer) => void} />
  return <section className="professional-market panel"><p className="eyebrow">MERCADO CONTÍNUO · CONTRATOS</p><h2>O próximo acordo começa aqui.</h2><p>Negocie durante toda a temporada. A assinatura confirma a mudança imediatamente. Valores e multas são estimativas do simulador.</p><div className="season-stats"><article><span>SEU SALÁRIO MENSAL</span><strong>{money(contract.wage)}</strong></article><article><span>SEU VÍNCULO</span><strong>{contract.seasons} temporadas</strong></article><article><span>SUA MULTA</span><strong>{money(contract.releaseClause)}</strong></article></div><label>Área do mercado<select value={kind} onChange={event => setKind(event.target.value)}><option value="self">Minha carreira · propostas de trabalho</option><option value="player">Atletas · compras e vendas</option>{career.mode === 'director' && <option value="coach">Treinadores</option>}</select></label>
    {kind === 'self' ? <div className="terms-grid"><label>Clube de destino<select value={destination} onChange={event => setDestination(event.target.value)}>{clubs.filter(club => club.id !== career.clubId).map(club => <option key={club.id} value={club.id}>{club.name}</option>)}</select></label><button className="secondary" onClick={() => onChange(openEmployment(career, 'self', destination))}>Consultar proposta e negociar</button><p>A compensação será paga pelo clube de destino. Seu calendário e seus números pessoais continuam.</p></div> : kind === 'player' ? <PlayerDossier career={career} onNegotiate={id => { const person = marketProfessionals(career).find(p => p.id === id); if (person) onChange(openEmployment(career, id, person.clubId === career.clubId ? clubs.find(club => club.id !== career.clubId)!.id : career.clubId)) }} /> : <><label>Pesquisar profissional<input value={search} onChange={event => setSearch(event.target.value)} placeholder="Digite um nome" /></label><div className="table-wrap"><table><thead><tr><th>Profissional</th><th>Clube</th><th>Salário</th><th>Multa</th><th>Negociar</th></tr></thead><tbody>{people.map(person => <tr key={person.id}><th>{person.name}</th><td>{clubName(person.clubId)}</td><td>{money(person.terms.wage)}</td><td>{money(person.terms.releaseClause)}</td><td><button className="table-action" disabled={person.kind === 'coach' && person.clubId === career.clubId} onClick={() => onChange(openEmployment(career, person.id, person.clubId === career.clubId ? clubs.find(club => club.id !== career.clubId)!.id : career.clubId))}>{person.clubId === career.clubId ? 'Ouvir oferta' : 'Abrir conversa'}</button></td></tr>)}</tbody></table></div></>}
    <h3>Mesa de negociações</h3>{!state.deals.length && <p>Nenhuma conversa aberta. Escolha um profissional ou um clube acima.</p>}{state.deals.slice().reverse().map(deal => <EmploymentEditor key={`${deal.id}-${deal.round}-${deal.status}`} deal={deal} onOffer={terms => onChange(offerEmployment(career, deal.id, terms))} onSign={() => onChange(signEmployment(career, deal.id))} onWithdraw={() => onChange(withdrawEmployment(career, deal.id))} />)}
  </section>
}
function PlayerOfferInbox({ career, onChange }: { career: PlayerCareer; onChange: (next: PlayerCareer) => void }) {
  const [counter, setCounter] = useState<Record<string, { wage: number; seasons: number }>>({})
  const activeOffers = career.offers.filter(offer => offer.status !== 'rejected')
  const marketValue = playerMarketValue(career)
  return <section className="professional-market player-offer-inbox panel"><p className="eyebrow">MERCADO DO JOGADOR</p><h2>{career.seasonComplete ? 'Propostas recebidas' : 'Clubes observando sua temporada'}</h2><p>{career.seasonComplete ? 'Os clubes chegaram até você. Compare salário, duração, papel no elenco e envie contraproposta antes de assinar.' : 'Você não abre negociação sozinho. Seu desempenho cria interesse, e as propostas aparecem ao fim da temporada.'}</p><div className="season-stats"><article><span>VALOR ESTIMADO</span><strong>{money(marketValue)}</strong><small>Baseado em idade, geral e produção</small></article><article><span>SALÁRIO ATUAL</span><strong>{money(career.contract.wage)}</strong><small>{career.contract.seasons} temporadas restantes</small></article><article><span>PARTICIPAÇÕES</span><strong>{career.stats.goals + career.stats.assists}</strong><small>{career.stats.goals} gols · {career.stats.assists} assist.</small></article></div>
    {!career.seasonComplete ? <section className="contract-scouting"><h3>O que aumenta seu mercado</h3><div className="player-objectives"><p className={career.stats.appearances >= 25 ? 'done' : ''}>Minutos e sequência <b>{career.stats.appearances}/25 jogos</b></p><p className={career.stats.goals + career.stats.assists >= 5 ? 'done' : ''}>Produção ofensiva <b>{career.stats.goals + career.stats.assists}/5</b></p><p className={career.trust >= 60 ? 'done' : ''}>Confiança interna <b>{career.trust}/60</b></p></div></section> : <div className="player-offer-grid">{activeOffers.map(offer => { const club = clubs.find(item => item.id === offer.clubId)!; const draft = counter[offer.clubId] ?? { wage: offer.wage, seasons: offer.seasons }; return <article className={`player-offer-card ${offer.status ?? 'received'}`} key={offer.clubId}><span className="crest" style={{ color: club.color, borderColor: club.color }}>{club.initials}</span><h3>{club.name}</h3><p>{offer.role}</p><strong>{money(offer.wage)}/mês</strong><small>{offer.seasons} temporadas · {offer.note ?? 'Proposta na mesa'}</small><div className="terms-grid"><label>Salário desejado<input type="number" min={1} step={1} value={draft.wage} onChange={event => setCounter({ ...counter, [offer.clubId]: { ...draft, wage: Number(event.target.value) } })} /></label><label>Duração<input type="number" min={1} max={5} step={1} value={draft.seasons} onChange={event => setCounter({ ...counter, [offer.clubId]: { ...draft, seasons: Number(event.target.value) } })} /></label></div><div className="deal-actions"><button className="primary" onClick={() => onChange(acceptPlayerOffer(career, offer.clubId))}>{offer.status === 'accepted' || offer.status === 'countered' ? 'Assinar acordo' : offer.clubId === career.clubId ? 'Renovar' : 'Aceitar'}</button><button className="secondary" onClick={() => onChange(counterPlayerOffer(career, offer.clubId, draft.wage, draft.seasons))}>Enviar contraproposta</button><button className="text-button" onClick={() => onChange(rejectPlayerOffer(career, offer.clubId))}>Recusar</button></div></article> })}</div>}
    {career.seasonComplete && !activeOffers.length && <p className="muted">Você recusou todas as propostas abertas. Se ainda tiver contrato, pode permanecer no clube atual.</p>}
    {career.seasonComplete && career.contract.seasons > 1 && <button className="secondary stay-button" onClick={() => onChange(stayUnderContract(career))}>Cumprir contrato atual e iniciar nova temporada</button>}
  </section>
}
function EmploymentEditor({ deal, onOffer, onSign, onWithdraw }: { deal: EmploymentDeal; onOffer: (terms: EmploymentTerms) => void; onSign: () => void; onWithdraw: () => void }) {
  const [terms, setTerms] = useState(deal.terms)
  const editable = ['draft', 'countered'].includes(deal.status)
  return <article className="deal-editor"><h3>{deal.name} · {clubName(deal.from)} → {clubName(deal.to)}</h3><p role="status">{deal.note}</p><div className="terms-grid">{([['fee', 'Compensação ao clube'], ['wage', 'Salário mensal'], ['seasons', 'Temporadas (1–5)'], ['releaseClause', 'Multa do novo contrato']] as const).map(([key, title]) => <label key={key}>{title}<input type="number" min={key === 'fee' ? 0 : 1} max={key === 'seasons' ? 5 : 100000000} step={1} disabled={!editable} value={terms[key]} onChange={event => setTerms({ ...terms, [key]: Number(event.target.value) })} /></label>)}</div>{deal.status === 'countered' && <p>Solicitado: compensação {money(deal.asking.fee)}, salário {money(deal.asking.wage)}, {deal.asking.seasons} temporadas, multa {money(deal.asking.releaseClause)}.</p>}<div className="deal-actions">{editable && <><button className="primary" onClick={() => onOffer(terms)}>Enviar proposta</button><button className="secondary" onClick={() => setTerms(deal.asking)}>Usar condições solicitadas</button><button className="secondary" onClick={() => setTerms({ ...terms, fee: deal.currentClause })}>Cobrir multa atual · {money(deal.currentClause)}</button></>}{deal.status === 'accepted' && <button className="primary" onClick={onSign}>Assinar e concluir agora</button>}{!['signed', 'withdrawn'].includes(deal.status) && <button className="text-button" onClick={onWithdraw}>Encerrar conversa</button>}</div></article>
}
