import { PlayerDossier } from './PlayerDossier'
import { useState } from 'react'
import { clubs } from './realData'
import { employmentOf, marketProfessionals, offerEmployment, openEmployment, ownEmployment, signEmployment, withdrawEmployment, type MarketCareer } from './professionalMarket'
import type { EmploymentDeal, EmploymentTerms } from './employment'

const money = (value: number) => `R$ ${value.toLocaleString('pt-BR')} mil`
const clubName = (id: string) => clubs.find(club => club.id === id)?.name ?? 'Sem clube'
export function ProfessionalMarket<T extends MarketCareer>({ career, onChange }: { career: T; onChange: (next: T) => void }) {
  const [search, setSearch] = useState(''), [kind, setKind] = useState('self'), [destination, setDestination] = useState(clubs.find(club => club.id !== career.clubId)!.id as string)
  const state = employmentOf(career), contract = ownEmployment(career), people = marketProfessionals(career).filter(person => person.kind === kind && person.name.toLocaleLowerCase('pt-BR').includes(search.toLocaleLowerCase('pt-BR')))
  return <section className="professional-market panel"><p className="eyebrow">MERCADO CONTÍNUO · CONTRATOS</p><h2>O próximo acordo começa aqui.</h2><p>Negocie durante toda a temporada. A assinatura confirma a mudança imediatamente. Valores e multas são estimativas do simulador.</p><div className="season-stats"><article><span>SEU SALÁRIO MENSAL</span><strong>{money(contract.wage)}</strong></article><article><span>SEU VÍNCULO</span><strong>{contract.seasons} temporadas</strong></article><article><span>SUA MULTA</span><strong>{money(contract.releaseClause)}</strong></article></div><label>Área do mercado<select value={kind} onChange={event => setKind(event.target.value)}><option value="self">Minha carreira · propostas de trabalho</option>{career.mode !== 'player' && <option value="player">Atletas · compras e vendas</option>}{career.mode === 'director' && <option value="coach">Treinadores</option>}</select></label>
    {kind === 'self' ? <div className="terms-grid"><label>Clube de destino<select value={destination} onChange={event => setDestination(event.target.value)}>{clubs.filter(club => club.id !== career.clubId).map(club => <option key={club.id} value={club.id}>{club.name}</option>)}</select></label><button className="secondary" onClick={() => onChange(openEmployment(career, 'self', destination))}>Consultar proposta e negociar</button><p>A compensação será paga pelo clube de destino. Seu calendário e seus números pessoais continuam.</p></div> : kind === 'player' ? <PlayerDossier career={career} onNegotiate={id => { const person = marketProfessionals(career).find(p => p.id === id); if (person) onChange(openEmployment(career, id, person.clubId === career.clubId ? clubs.find(club => club.id !== career.clubId)!.id : career.clubId)) }} /> : <><label>Pesquisar profissional<input value={search} onChange={event => setSearch(event.target.value)} placeholder="Digite um nome" /></label><div className="table-wrap"><table><thead><tr><th>Profissional</th><th>Clube</th><th>Salário</th><th>Multa</th><th>Negociar</th></tr></thead><tbody>{people.map(person => <tr key={person.id}><th>{person.name}</th><td>{clubName(person.clubId)}</td><td>{money(person.terms.wage)}</td><td>{money(person.terms.releaseClause)}</td><td><button className="table-action" disabled={person.kind === 'coach' && person.clubId === career.clubId} onClick={() => onChange(openEmployment(career, person.id, person.clubId === career.clubId ? clubs.find(club => club.id !== career.clubId)!.id : career.clubId))}>{person.clubId === career.clubId ? 'Ouvir oferta' : 'Abrir conversa'}</button></td></tr>)}</tbody></table></div></>}
    <h3>Mesa de negociações</h3>{!state.deals.length && <p>Nenhuma conversa aberta. Escolha um profissional ou um clube acima.</p>}{state.deals.slice().reverse().map(deal => <EmploymentEditor key={`${deal.id}-${deal.round}-${deal.status}`} deal={deal} onOffer={terms => onChange(offerEmployment(career, deal.id, terms))} onSign={() => onChange(signEmployment(career, deal.id))} onWithdraw={() => onChange(withdrawEmployment(career, deal.id))} />)}
  </section>
}
function EmploymentEditor({ deal, onOffer, onSign, onWithdraw }: { deal: EmploymentDeal; onOffer: (terms: EmploymentTerms) => void; onSign: () => void; onWithdraw: () => void }) {
  const [terms, setTerms] = useState(deal.terms)
  const editable = ['draft', 'countered'].includes(deal.status)
  return <article className="deal-editor"><h3>{deal.name} · {clubName(deal.from)} → {clubName(deal.to)}</h3><p role="status">{deal.note}</p><div className="terms-grid">{([['fee', 'Compensação ao clube'], ['wage', 'Salário mensal'], ['seasons', 'Temporadas (1–5)'], ['releaseClause', 'Multa do novo contrato']] as const).map(([key, title]) => <label key={key}>{title}<input type="number" min={key === 'fee' ? 0 : 1} max={key === 'seasons' ? 5 : 100000000} step={1} disabled={!editable} value={terms[key]} onChange={event => setTerms({ ...terms, [key]: Number(event.target.value) })} /></label>)}</div>{deal.status === 'countered' && <p>Solicitado: compensação {money(deal.asking.fee)}, salário {money(deal.asking.wage)}, {deal.asking.seasons} temporadas, multa {money(deal.asking.releaseClause)}.</p>}<div className="deal-actions">{editable && <><button className="primary" onClick={() => onOffer(terms)}>Enviar proposta</button><button className="secondary" onClick={() => setTerms(deal.asking)}>Usar condições solicitadas</button><button className="secondary" onClick={() => setTerms({ ...terms, fee: deal.currentClause })}>Cobrir multa atual · {money(deal.currentClause)}</button></>}{deal.status === 'accepted' && <button className="primary" onClick={onSign}>Assinar e concluir agora</button>}{!['signed', 'withdrawn'].includes(deal.status) && <button className="text-button" onClick={onWithdraw}>Encerrar conversa</button>}</div></article>
}
