import { useState } from 'react'
import type { Career } from './model'

const keys = ['vt27.career.v1', 'vt27.player-career.v1', 'vt27.director-career.v1']
export function Tutorial({ onClose }: { onClose: () => void }) {
  const [step, setStep] = useState(0)
  const steps = [
    ['ESCOLHA SUA HISTÓRIA', 'Treinador, jogador e dirigente vivem o mesmo universo por perspectivas diferentes. Você pode manter uma carreira salva em cada modo.'],
    ['PREPARE O TIME', 'No modo treinador, use Prancheta para escalar e definir a identidade; Calendário para equilibrar treino, ritmo e recuperação.'],
    ['DECIDA E EVOLUA', 'Partidas, diretoria, mercado e mundo reagem às suas escolhas. Toda ação importante mostra efeitos e exige confirmação.'],
    ['SEU PROGRESSO', 'O jogo salva neste navegador. Em Segurança e save, exporte um backup e configure um PIN local para sua sessão.'],
  ]
  const finish = () => { localStorage.setItem('vt27.tutorial.done', '1'); onClose() }
  return <div className="tutorial-backdrop" role="dialog" aria-modal="true" aria-labelledby="tutorial-title"><section className="tutorial-card"><div className="tutorial-progress">{steps.map((_, index) => <span className={index <= step ? 'active' : ''} key={index} />)}</div><p className="eyebrow">GUIA RÁPIDO · {step + 1}/{steps.length}</p><h2 id="tutorial-title">{steps[step][0]}</h2><p>{steps[step][1]}</p><div className="tutorial-visual" aria-hidden="true"><b>{String(step + 1).padStart(2, '0')}</b><span>VT27</span></div><div className="tutorial-actions"><button className="text-button" onClick={finish}>Pular guia</button>{step > 0 && <button className="secondary" onClick={() => setStep(value => value - 1)}>Voltar</button>}<button className="primary" onClick={() => step === steps.length - 1 ? finish() : setStep(value => value + 1)}>{step === steps.length - 1 ? 'Entrar no jogo' : 'Continuar →'}</button></div></section></div>
}

export function AccessGate({ onUnlock }: { onUnlock: () => void }) {
  const [pin, setPin] = useState(''); const [error, setError] = useState('')
  function unlock() { if (pin === localStorage.getItem('vt27.access.pin')) { sessionStorage.setItem('vt27.unlocked', '1'); onUnlock() } else setError('PIN incorreto. Tente novamente.') }
  return <main className="access-gate"><div className="gate-brand">VT<span>27</span></div><p className="eyebrow">CARREIRA PROTEGIDA</p><h1>Bem-vindo de volta.</h1><p>Digite seu PIN local para abrir o centro de carreira.</p><form onSubmit={event => { event.preventDefault(); unlock() }}><label htmlFor="access-pin">PIN de acesso</label><input id="access-pin" inputMode="numeric" type="password" minLength={4} maxLength={8} value={pin} onChange={event => setPin(event.target.value.replace(/\D/g, ''))} autoFocus /><button className="primary">Desbloquear →</button></form>{error && <p className="gate-error" role="alert">{error}</p>}</main>
}

export function SecurityPanel({ career }: { career: Career }) {
  const [pin, setPin] = useState(''); const [confirm, setConfirm] = useState(''); const [message, setMessage] = useState('')
  function exportSave() { const data = Object.fromEntries(keys.map(key => [key, localStorage.getItem(key)]).filter(([, value]) => value)); const blob = new Blob([JSON.stringify({ product: 'VT27', version: 1, exportedAt: new Date().toISOString(), saves: data }, null, 2)], { type: 'application/json' }); const url = URL.createObjectURL(blob); const anchor = document.createElement('a'); anchor.href = url; anchor.download = `vt27-backup-${new Date().toISOString().slice(0, 10)}.json`; anchor.click(); URL.revokeObjectURL(url); setMessage('Backup exportado com sucesso.') }
  async function importSave(file?: File) { try { if (!file) return; const parsed = JSON.parse(await file.text()); if (parsed?.product !== 'VT27' || !parsed.saves) throw new Error(); keys.forEach(key => { if (typeof parsed.saves[key] === 'string') JSON.parse(parsed.saves[key]) }); keys.forEach(key => { if (typeof parsed.saves[key] === 'string') localStorage.setItem(key, parsed.saves[key]) }); setMessage('Backup restaurado. Recarregue a página para abrir as carreiras importadas.') } catch { setMessage('Arquivo inválido. Nenhum save foi alterado.') } }
  function savePin() { if (!/^\d{4,8}$/.test(pin) || pin !== confirm) return setMessage('Use de 4 a 8 números iguais nos dois campos.'); localStorage.setItem('vt27.access.pin', pin); sessionStorage.setItem('vt27.unlocked', '1'); setPin(''); setConfirm(''); setMessage('PIN local ativado. Ele será solicitado ao reabrir o jogo.') }
  function removePin() { localStorage.removeItem('vt27.access.pin'); sessionStorage.removeItem('vt27.unlocked'); setMessage('PIN removido.') }
  return <section className="security-center"><section className="security-hero"><div><p className="eyebrow">SEGURANÇA E CONTINUIDADE</p><h2>Sua carreira, sob seu controle.</h2><p>Proteja o acesso neste dispositivo e leve um backup dos três modos.</p></div><strong>T{career.seasonNumber ?? 1}</strong></section><div className="security-grid"><section><span className="tool-number">01</span><h2>Backup do universo</h2><p>O arquivo reúne treinador, jogador e dirigente. Guarde uma cópia antes de trocar de navegador ou dispositivo.</p><button className="primary" onClick={exportSave}>Exportar backup</button><label className="import-button">Importar backup<input type="file" accept="application/json" onChange={event => importSave(event.target.files?.[0])} /></label></section><section><span className="tool-number">02</span><h2>PIN local</h2><p>O PIN bloqueia a abertura do jogo neste navegador. Ele não substitui a segurança da sua conta ou do dispositivo.</p><div className="pin-fields"><input aria-label="Novo PIN" inputMode="numeric" type="password" placeholder="Novo PIN" value={pin} onChange={event => setPin(event.target.value.replace(/\D/g, ''))} maxLength={8} /><input aria-label="Confirmar PIN" inputMode="numeric" type="password" placeholder="Confirmar PIN" value={confirm} onChange={event => setConfirm(event.target.value.replace(/\D/g, ''))} maxLength={8} /></div><button className="secondary" onClick={savePin}>Ativar ou trocar PIN</button>{localStorage.getItem('vt27.access.pin') && <button className="text-button" onClick={removePin}>Remover PIN</button>}</section></div>{message && <p className="market-message" role="status">{message}</p>}<details className="rules-explainer"><summary>Onde o progresso fica salvo?</summary><p>Os saves continuam armazenados neste navegador. O backup JSON permite copiar e restaurar os três modos manualmente. A importação valida a estrutura geral antes de substituir os dados locais.</p></details></section>
}

