import { advanceDay, isMatchDay, progressMatch } from './season'
import { useRef } from 'react'
import { clubs, type Career } from './model'
import { lineupOf, player, score, simulate, strength } from './football'
export function Friendly({ career, onChange, onLineup, onSchedule }: { career: Career; onChange: (career: Career) => void; onLineup: () => void; onSchedule: () => void }) {
  const starting = useRef(false)
  const club = clubs.find(c => c.id === career.clubId)!
  const match = career.match
  const opponents = clubs.filter(c => c.id !== career.clubId)
  const opponent = match ? clubs.find(c => c.id === match.opponent)! : opponents[Math.floor(((career.day ?? 1) - 1) / 3) % opponents.length]
  const total = match ? score(match) : { home: 0, away: 0 }
  const finished = !!match && match.cursor === match.events.length
  const events = match?.events.slice(0, match.cursor) ?? []
  if (!isMatchDay(career)) return <section className="panel"><p className="eyebrow">CALENDÁRIO</p><h2>{(career.day ?? 1) > 7 ? 'Pré-temporada concluída.' : 'Hoje é dia de preparação.'}</h2><p>Consulte sua agenda para treinar, recuperar os atletas ou rever os resultados.</p><button className="primary" onClick={onSchedule}>Abrir calendário →</button></section>
  return <div className="match-center"><div className="match-heading"><p className="eyebrow">PRÉ-TEMPORADA / AMISTOSO {Math.floor(((career.day ?? 1) - 1) / 3) + 1}</p><span className="badge active">{finished ? 'ENCERRADO' : match ? 'EM ANDAMENTO' : 'PRONTO PARA COMEÇAR'}</span></div>
    <section className="scoreboard" aria-label="Placar do amistoso"><div className="score-team"><span className="match-crest" style={{ color: club.color }}>{club.initials}</span><h2>{club.name}</h2><span>SEU TIME</span></div><div className="score-middle"><span className="match-clock">{finished ? 'FIM DE JOGO' : match ? `${match.cursor * 10}′` : 'PRÉ-JOGO'}</span><strong aria-label={`${club.name} ${total.home}, ${opponent.name} ${total.away}`}>{match ? `${total.home} : ${total.away}` : 'VS'}</strong><span>AMISTOSO · EM CASA</span></div><div className="score-team"><span className="match-crest" style={{ color: opponent.color }}>{opponent.initials}</span><h2>{opponent.name}</h2><span>VISITANTE</span></div></section>
    {!match && <section className="panel kickoff-panel"><div><p className="eyebrow">ÚLTIMA CONVERSA NO VESTIÁRIO</p><h2>É hora de testar suas ideias.</h2><p>{career.formation} · 11 titulares · Força {strength(lineupOf(career), career.formation, career)} contra um adversário de força 70.</p><p className="muted">Você acompanha nove lances, avançando no seu ritmo. O resultado considera a escalação e o acaso. Nesta etapa não há substituições durante o jogo.</p></div><div className="match-actions"><button className="secondary" onClick={onLineup}>Revisar escalação</button><button className="primary" onClick={() => { if (starting.current) return; starting.current = true; onChange({ ...career, match: simulate(career) }) }}>Iniciar amistoso <span aria-hidden="true">→</span></button></div></section>}
    {match && !finished && <div className="match-controls"><div><strong>{match.cursor === 0 ? 'Bola no centro. Tudo pronto!' : 'O jogo continua.'}</strong><p>Avance para revelar o próximo lance. Você pode sair e retomar depois.</p></div><button className="primary" onClick={() => onChange(progressMatch(career, match.cursor + 1))}>Próximo lance <span aria-hidden="true">▶</span></button><button className="secondary" onClick={() => onChange(progressMatch(career, match.events.length))}>Ver resultado final</button></div>}
    <div className="match-live-status" role="status" aria-live="polite">{events.length > 0 && `${events.at(-1)!.minute} minutos. ${events.at(-1)!.text} Placar: ${total.home} a ${total.away}.`}</div>
    {match && <section className="match-content"><div className="panel"><p className="eyebrow">LANCES DA PARTIDA</p>{events.length === 0 && <p className="muted">O primeiro lance aparece ao avançar a partida.</p>}<ol className="event-feed">{[...events].reverse().map(event => <li className={event.goal ? 'goal-event' : ''} key={event.minute}><time>{event.minute}′</time><div><small>{event.goal ? 'GOL' : 'OPORTUNIDADE'} · {event.side === 'home' ? club.name : opponent.name}</small><p>{event.text}</p></div></li>)}</ol></div>
      <section className="panel"><p className="eyebrow">{finished ? 'BALANÇO DO AMISTOSO' : 'ESCALAÇÃO EM CAMPO'}</p>{finished ? <><h2>{total.home > total.away ? 'Um teste com vitória.' : total.home === total.away ? 'Equilíbrio no amistoso.' : 'Um teste para aprender.'}</h2><p>Seu time converteu {total.home} de {events.filter(e => e.side === 'home').length} oportunidades. O adversário marcou {total.away} em {events.filter(e => e.side === 'away').length}.</p><p className="muted">As notas combinam variação de desempenho, gols e resultado coletivo nesta simulação inicial.</p><h3>Notas dos titulares</h3><div className="player-ratings">{match.ratings.map(r => <div key={r.playerId}><span>{player(r.playerId).name}</span><strong>{r.value.toFixed(1)}</strong></div>)}</div></> : <><h2>{match.formation}</h2><p className="muted">Força no início: {match.strength}</p><ul className="match-lineup">{match.lineup.map(id => <li key={id}><span>{player(id).position}</span>{player(id).name}</li>)}</ul></>}</section></section>}
    {finished && <section className="next-day"><div><h2>Teste concluído. Hora de recuperar.</h2><p>Os titulares receberam o desgaste da partida. Avance para arquivar este resultado e recuperar 8 de energia com o descanso.</p></div><button className="primary" onClick={() => { onChange(advanceDay(career)); onSchedule() }}>Avançar para o dia {(career.day ?? 1) + 1} →</button></section>}
  </div>
}
