import { leagueFixture } from './league'
import { cupFixture } from './cup'
import { cupDayInfo, cupStageNames } from './cupData'
import { advanceDay, isMatchDay, progressMatch } from './season'
import { useRef } from 'react'
import { allClubs, clubs, type Career } from './model'
import { lineupOf, player, score, simulate, strength } from './football'
import { unavailableLineup } from './availability'
import { MatchManagement } from './MatchManagement'
export function Friendly({ career, onChange, onLineup, onSchedule }: { career: Career; onChange: (career: Career) => void; onLineup: () => void; onSchedule: () => void }) {
  const starting = useRef(false)
  const club = clubs.find(c => c.id === career.clubId)!
  const match = career.match
  const cup = cupFixture(career)
  const fixture = cup ?? leagueFixture(career)
  const cupInfo = cupDayInfo(career.day ?? 1)
  const opponents = clubs.filter(c => c.id !== career.clubId)
  const opponent = match ? allClubs.find(c => c.id === match.opponent)! : fixture ? allClubs.find(c => c.id === fixture.opponent)! : opponents[Math.floor(((career.day ?? 1) - 1) / 3) % opponents.length]
  const total = match ? score(match) : { home: 0, away: 0 }
  const finished = !!match && match.cursor === match.events.length
  const events = match?.events.slice(0, match.cursor) ?? []
  const blocked = unavailableLineup(career)
  if (!isMatchDay(career) && !match) return <section className="panel"><p className="eyebrow">CALENDÁRIO</p><h2>{(career.day ?? 1) > (career.leagueActive ? 120 : 7) ? 'Etapa concluída.' : 'Hoje é dia de preparação.'}</h2><p>Consulte sua agenda para treinar, recuperar os atletas ou rever os resultados.</p><button className="primary" onClick={onSchedule}>Abrir calendário →</button></section>
  const competition = cupInfo ? `COPA DO BRASIL / ${cupStageNames[cupInfo.stage].toUpperCase()}${cupInfo.stage === 9 ? '' : ` · JOGO ${cupInfo.leg}`}` : fixture && 'round' in fixture ? 'BRASILEIRÃO / RODADA ' + fixture.round : 'PRÉ-TEMPORADA / AMISTOSO ' + (Math.floor(((career.day ?? 1) - 1) / 3) + 1)
  const savedCupResult = cupInfo ? career.cup?.results.find(result => result.stage === cupInfo.stage && result.leg === cupInfo.leg && [result.home, result.away].includes(career.clubId)) : undefined
  const atHome = cup ? cup.atHome : savedCupResult ? savedCupResult.home === career.clubId : fixture && 'atHome' in fixture ? fixture.atHome : true
  return <div className="match-center"><div className="match-heading"><p className="eyebrow">{competition}</p><span className="badge active">{finished ? 'ENCERRADO' : match ? 'EM ANDAMENTO' : 'PRONTO PARA COMEÇAR'}</span></div>
    <section className="scoreboard" aria-label="Placar da partida"><div className="score-team"><span className="match-crest" style={{ color: club.color }}>{club.initials}</span><h2>{club.name}</h2><span>SEU TIME</span></div><div className="score-middle"><span className="match-clock">{finished ? 'FIM DE JOGO' : match ? `${match.cursor * 10}′` : 'PRÉ-JOGO'}</span><strong aria-label={`${club.name} ${total.home}, ${opponent.name} ${total.away}`}>{match ? `${total.home} : ${total.away}` : 'VS'}</strong><span>{cupInfo ? 'COPA DO BRASIL' : fixture ? 'BRASILEIRÃO' : 'AMISTOSO'} · {atHome ? 'EM CASA' : 'FORA DE CASA'}</span></div><div className="score-team"><span className="match-crest" style={{ color: opponent.color }}>{opponent.initials}</span><h2>{opponent.name}</h2><span>{!atHome ? 'MANDANTE' : 'VISITANTE'}</span></div></section>
    {!match && <section className="panel kickoff-panel"><div><p className="eyebrow">ÚLTIMA CONVERSA NO VESTIÁRIO</p><h2>{blocked.length ? 'A escalação precisa de ajustes.' : 'É hora de testar suas ideias.'}</h2><p>{career.formation} · 11 titulares · Força {strength(lineupOf(career), career.formation, career)} contra um adversário de força 70.</p><p className="muted">{blocked.length ? `${blocked.map(id => player(id).name).join(', ')} não pode jogar. Troque os atletas indisponíveis antes da partida.` : 'Você acompanha nove lances no seu ritmo e pode ajustar a mentalidade e fazer até três substituições.'}</p></div><div className="match-actions"><button className="secondary" onClick={onLineup}>Revisar escalação</button><button className="primary" disabled={!!blocked.length} onClick={() => { if (starting.current || blocked.length) return; starting.current = true; onChange({ ...career, match: simulate(career) }) }}>{fixture ? 'Iniciar partida' : 'Iniciar amistoso'} <span aria-hidden="true">→</span></button></div></section>}
    {match && !finished && <div className="match-controls"><div><strong>{match.cursor === 0 ? 'Bola no centro. Tudo pronto!' : 'O jogo continua.'}</strong><p>Avance para revelar o próximo lance. Você pode sair e retomar depois.</p></div><button className="primary" onClick={() => onChange(progressMatch(career, match.cursor + 1))}>Próximo lance <span aria-hidden="true">▶</span></button><button className="secondary" onClick={() => onChange(progressMatch(career, match.events.length))}>Ver resultado final</button></div>}
    {match && !finished && <MatchManagement career={career} onChange={onChange} />}
    <div className="match-live-status" role="status" aria-live="polite">{events.length > 0 && `${events.at(-1)!.minute} minutos. ${events.at(-1)!.text} Placar: ${total.home} a ${total.away}.`}</div>
    {match && <section className="match-content"><div className="panel"><p className="eyebrow">LANCES DA PARTIDA</p>{events.length === 0 && <p className="muted">O primeiro lance aparece ao avançar a partida.</p>}<ol className="event-feed">{[...events].reverse().map(event => <li className={event.goal ? 'goal-event' : ''} key={event.minute}><time>{event.minute}′</time><div><small>{event.goal ? 'GOL' : 'OPORTUNIDADE'} · {event.side === 'home' ? club.name : opponent.name}</small><p>{event.text}</p></div></li>)}</ol></div>
      <section className="panel"><p className="eyebrow">{finished ? 'BALANÇO DA PARTIDA' : 'ESCALAÇÃO EM CAMPO'}</p>{finished ? <><h2>{total.home > total.away ? 'Vitória para o seu time.' : total.home === total.away ? 'Equilíbrio no placar.' : 'Um teste para aprender.'}</h2><p>Seu time converteu {total.home} de {events.filter(e => e.side === 'home').length} oportunidades. O adversário marcou {total.away} em {events.filter(e => e.side === 'away').length}.</p><p className="muted">As notas consideram o resultado, os gols e os minutos em campo nesta simulação.</p>{(!!match.yellowCards?.length || match.injury) && <div className="match-incidents"><h3>Boletim médico e disciplinar</h3>{match.yellowCards?.map(id => <p key={id}><span className="yellow-card" /> Cartão amarelo · {player(id).name}</p>)}{match.injury && <p><span className="injury-mark">✚</span> Lesão · {player(match.injury.playerId).name} · fora por {match.injury.matches} {match.injury.matches === 1 ? 'jogo' : 'jogos'}</p>}</div>}<h3>Notas dos participantes</h3><div className="player-ratings">{match.ratings.map(r => <div key={r.playerId}><span>{player(r.playerId).name}</span><strong>{r.value.toFixed(1)}</strong></div>)}</div>{!!match.substitutions?.length && <><h3>Substituições</h3><div className="substitution-history">{match.substitutions.map(change => <p key={change.minute + change.outId}><time>{change.minute}′</time> {player(change.outId).name} → {player(change.inId).name}</p>)}</div></>}</> : <><h2>{match.formation}</h2><p className="muted">Força no início: {match.strength} · Postura: {match.mentality === 'attacking' ? 'ofensiva' : match.mentality === 'defensive' ? 'defensiva' : 'equilibrada'}</p><ul className="match-lineup">{match.lineup.map(id => <li key={id}><span>{player(id).position}</span>{player(id).name}</li>)}</ul></>}</section></section>}
    {finished && <section className="next-day"><div><h2>Jogo concluído. Hora de recuperar.</h2><p>Desgaste, cartões e possíveis lesões já foram registrados. Avance para arquivar o resultado e cumprir uma partida das ausências anteriores.</p></div><button className="primary" onClick={() => { onChange(advanceDay(career)); onSchedule() }}>Avançar para o dia {(career.day ?? 1) + 1} →</button></section>}
  </div>
}
