import { useState } from 'react'
import { conditionLabel, unavailable } from './availability'
import { autoLineup, fit, lineupOf, player, strength, swap } from './football'
import { rosterOf, type Career } from './model'
import { overall } from './progression'
import { energy } from './season'
import { tacticsOf } from './tactics'
import { positions, type Formation, type TacticalPlan } from './types'

type Filter = 'all' | 'starters' | 'reserves' | string
const tacticalOptions: { key: keyof TacticalPlan; title: string; choices: { value: string; label: string; effect: string }[] }[] = [
  { key: 'pressure', title: 'Pressão', choices: [{ value: 'low', label: 'Recuada', effect: 'Poupa energia e protege espaço.' }, { value: 'balanced', label: 'Equilibrada', effect: 'Risco e desgaste controlados.' }, { value: 'high', label: 'Alta', effect: 'Recupera antes, mas cansa mais.' }] },
  { key: 'defensiveLine', title: 'Linha defensiva', choices: [{ value: 'low', label: 'Baixa', effect: 'Protege as costas da defesa.' }, { value: 'balanced', label: 'Média', effect: 'Mantém o bloco organizado.' }, { value: 'high', label: 'Alta', effect: 'Comprime o campo e oferece risco.' }] },
  { key: 'width', title: 'Largura', choices: [{ value: 'narrow', label: 'Estreita', effect: 'Concentra jogadores por dentro.' }, { value: 'balanced', label: 'Equilibrada', effect: 'Ocupa todos os corredores.' }, { value: 'wide', label: 'Aberta', effect: 'Explora pontas e laterais.' }] },
  { key: 'tempo', title: 'Ritmo com a bola', choices: [{ value: 'patient', label: 'Paciente', effect: 'Controla posse e economiza energia.' }, { value: 'balanced', label: 'Equilibrado', effect: 'Alterna controle e aceleração.' }, { value: 'fast', label: 'Rápido', effect: 'Cria mais perigo e mais desgaste.' }] },
  { key: 'focus', title: 'Construção', choices: [{ value: 'center', label: 'Por dentro', effect: 'Aproxima meio-campo e ataque.' }, { value: 'balanced', label: 'Variada', effect: 'Evita um padrão previsível.' }, { value: 'flanks', label: 'Pelos lados', effect: 'Busca amplitude e cruzamentos.' }] },
]

export function Lineup({ career, onChange }: { career: Career; onChange: (career: Career) => void }) {
  const [selected, setSelected] = useState(0)
  const [candidateId, setCandidateId] = useState<string>()
  const [filter, setFilter] = useState<Filter>('all')
  const ids = lineupOf(career)
  const roster = rosterOf(career)
  const locked = !!career.match && career.match.cursor < career.match.events.length
  const slots = positions[career.formation]
  const current = player(ids[selected])
  const candidate = candidateId ? roster.find(item => item.id === candidateId) : undefined
  const reserves = roster.filter(item => !ids.includes(item.id))
  const blocked = ids.filter(id => unavailable(career, id))
  const improvised = ids.filter((id, index) => fit(id, slots[index]) < 1)
  const tired = ids.filter(id => energy(career, id) < 55)
  const sizes = [1, ...career.formation.split('-').map(Number)]
  let offset = 0
  const rows = sizes.map(size => { const start = offset; offset += size; return Array.from({ length: size }, (_, index) => start + index) }).reverse()
  const candidates = roster.filter(item => selected === 0 ? item.position === 'GOL' : item.position !== 'GOL').filter(item => filter === 'all' || filter === 'starters' && ids.includes(item.id) || filter === 'reserves' && !ids.includes(item.id) || item.position === filter)
  const plan = tacticsOf(career)
  function chooseSlot(slot: number) { setSelected(slot); setCandidateId(undefined) }
  function confirmSwap() { if (!candidate || locked) return; const next = swap(ids, selected, candidate.id); if (next !== ids) onChange({ ...career, lineup: next }); setCandidateId(undefined) }
  function chooseFormation(formation: Formation) { if (locked) return; onChange({ ...career, formation, lineup: autoLineup(career, formation) }); setSelected(0); setCandidateId(undefined) }
  function updateTactic(key: keyof TacticalPlan, value: string) { if (!locked) onChange({ ...career, tactics: { ...plan, [key]: value } as TacticalPlan }) }
  return <section className="lineup-workspace lineup-v2"><div className="lineup-toolbar"><div><p className="eyebrow">CENTRAL DE ESCALAÇÃO E TÁTICAS</p><h2>Onze titulares. Um plano claro.</h2><p className="muted">Os titulares aparecem no campo e as reservas logo abaixo. Escolha uma posição, compare e confirme a troca.</p></div><div className="team-power"><strong>{strength(ids, career.formation, career)}</strong><span>FORÇA DO TIME</span></div></div>
    {locked && <p className="info-banner">A partida está em andamento. Escalação e plano tático estão bloqueados até o apito final.</p>}
    <div className="lineup-status-grid"><article className={blocked.length ? 'warning' : 'ready'}><span>TITULARES</span><strong>11/11</strong><small>{blocked.length ? `${blocked.length} indisponível(is)` : 'Todos disponíveis'}</small></article><article className={improvised.length ? 'warning' : 'ready'}><span>POSICIONAMENTO</span><strong>{improvised.length}</strong><small>improvisado(s)</small></article><article className={tired.length ? 'warning' : 'ready'}><span>ENERGIA BAIXA</span><strong>{tired.length}</strong><small>abaixo de 55%</small></article><article><span>BANCO</span><strong>{reserves.length}</strong><small>reservas disponíveis</small></article></div>
    <div className="lineup-actions"><fieldset className="formation-pills" disabled={locked}><legend>Formação</legend>{(Object.keys(positions) as Formation[]).map(value => <label className={value === career.formation ? 'chosen' : ''} key={value}><input type="radio" checked={value === career.formation} onChange={() => chooseFormation(value)} />{value}</label>)}</fieldset><button className="secondary" disabled={locked} onClick={() => onChange({ ...career, lineup: autoLineup(career) })}>Escalar melhor time disponível</button></div>
    <div className="lineup-layout"><div><div className="interactive-pitch"><div className="pitch-half" />{rows.map((row, rowIndex) => <div className="lineup-row" key={rowIndex}>{row.map(slot => { const athlete = player(ids[slot]); const absent = unavailable(career, athlete.id); return <button aria-pressed={selected === slot} aria-label={`${slots[slot]}: ${athlete.name}. Titular. ${conditionLabel(career, athlete.id)}.`} className={`pitch-athlete ${selected === slot ? 'selected-athlete' : ''} ${absent ? 'unavailable-athlete' : ''}`} key={slot} onClick={() => chooseSlot(slot)}><span className="lineup-state">TITULAR · {slots[slot]}</span><span className="jersey">{overall(career, athlete.id)}</span><strong>{athlete.name.split(' ').at(-1)}</strong><small>{absent ? conditionLabel(career, athlete.id) : `${energy(career, athlete.id)}% energia`}</small>{fit(athlete.id, slots[slot]) < 1 && <small className="position-warning">Fora da posição</small>}</button> })}</div>)}</div><div className="reserve-strip"><div><strong>BANCO DE RESERVAS</strong><span>{reserves.length} atletas fora do onze inicial</span></div>{reserves.map(athlete => <button disabled={locked || unavailable(career, athlete.id)} className={candidateId === athlete.id ? 'chosen' : ''} key={athlete.id} onClick={() => setCandidateId(athlete.id)}><span>{athlete.position}</span><strong>{athlete.name.split(' ').at(-1)}</strong><b>{overall(career, athlete.id)}</b><small>{unavailable(career, athlete.id) ? conditionLabel(career, athlete.id) : `${energy(career, athlete.id)}%`}</small></button>)}</div></div>
      <section className="bench-panel"><p className="eyebrow">ESPAÇO SELECIONADO · {slots[selected]}</p><h2>{current.name}</h2><div className="selection-badge">TITULAR NESTA POSIÇÃO</div><div className="comparison-current"><span><small>NÍVEL</small><strong>{overall(career, current.id)}</strong></span><span><small>ENERGIA</small><strong>{Math.round(energy(career, current.id))}%</strong></span><span><small>ADEQUAÇÃO</small><strong>{Math.round(fit(current.id, slots[selected]) * 100)}%</strong></span></div><div className="candidate-filters"><button className={filter === 'all' ? 'active' : ''} onClick={() => setFilter('all')}>Todos</button><button className={filter === 'reserves' ? 'active' : ''} onClick={() => setFilter('reserves')}>Reservas</button>{[...new Set(roster.map(item => item.position))].map(position => <button className={filter === position ? 'active' : ''} key={position} onClick={() => setFilter(position)}>{position}</button>)}</div><div className="candidate-list">{candidates.map(athlete => { const starter = ids.includes(athlete.id); const absent = unavailable(career, athlete.id); return <button disabled={locked || ids[selected] === athlete.id || absent} key={athlete.id} className={`candidate ${starter ? 'starter' : ''} ${candidateId === athlete.id ? 'candidate-selected' : ''} ${absent ? 'candidate-unavailable' : ''}`} onClick={() => setCandidateId(athlete.id)}><span className="candidate-position">{athlete.position}</span><span><strong>{athlete.name}</strong><small>{absent ? conditionLabel(career, athlete.id) : starter ? 'TITULAR · troca de posição' : 'RESERVA · disponível'}</small></span><b>{overall(career, athlete.id)}<small>{Math.round(energy(career, athlete.id))}%</small></b></button> })}</div>{candidate && <div className="swap-confirm"><p><strong>{candidate.name}</strong> entra em {slots[selected]} no lugar de {current.name}.</p><div className="swap-comparison"><span>Nível <b>{overall(career, current.id)} → {overall(career, candidate.id)}</b></span><span>Energia <b>{Math.round(energy(career, current.id))}% → {Math.round(energy(career, candidate.id))}%</b></span><span>Adequação <b>{Math.round(fit(current.id, slots[selected]) * 100)}% → {Math.round(fit(candidate.id, slots[selected]) * 100)}%</b></span></div><button className="primary" onClick={confirmSwap}>Confirmar troca</button><button className="text-button" onClick={() => setCandidateId(undefined)}>Cancelar</button></div>}</section></div>
    <section className="tactical-board"><div className="section-heading"><div><p className="eyebrow">PLANO TÁTICO</p><h2>Como o time deve jogar?</h2></div><span className="muted">Combinações coerentes aumentam a força; intensidade aumenta o desgaste.</span></div><div className="tactical-control-grid">{tacticalOptions.map(setting => <fieldset disabled={locked} key={setting.key}><legend>{setting.title}</legend>{setting.choices.map(choice => <label className={plan[setting.key] === choice.value ? 'selected' : ''} key={choice.value}><input type="radio" name={setting.key} checked={plan[setting.key] === choice.value} onChange={() => updateTactic(setting.key, choice.value)} /><strong>{choice.label}</strong><small>{choice.effect}</small></label>)}</fieldset>)}</div><div className="tactical-summary"><strong>IDENTIDADE ATUAL</strong><span>{plan.pressure === 'high' ? 'Pressão alta' : plan.pressure === 'low' ? 'Bloco recuado' : 'Pressão equilibrada'}</span><span>{plan.width === 'wide' ? 'Campo aberto' : plan.width === 'narrow' ? 'Time compacto' : 'Largura equilibrada'}</span><span>{plan.tempo === 'fast' ? 'Ritmo acelerado' : plan.tempo === 'patient' ? 'Posse paciente' : 'Ritmo equilibrado'}</span></div></section>
    <details className="rules-explainer"><summary>Como escalação e tática influenciam a partida?</summary><p>Nível, posição natural e energia formam a força de cada titular. A escalação automática escolhe o melhor time disponível para a formação. O plano tático acrescenta bônus quando formação, largura e construção combinam, enquanto pressão alta e ritmo rápido aumentam o desgaste. Linha alta e jogo acelerado também deixam mais espaço para o adversário.</p></details></section>
}

