import { useState } from 'react'
import { allPlayers, defaultLineupFor, marketPlayers, rosterOf, type Career } from './model'
import { overall } from './progression'
import { buyPlayer, contractsOf, financesOf, renewContract, sellPlayer, wageUsed } from './transfers'

const money = (value: number) => value >= 1000 ? `R$ ${(value / 1000).toFixed(1).replace('.', ',')} mi` : `R$ ${value} mil`
export function Market({ career, onChange }: { career: Career; onChange: (career: Career) => void }) {
  const [message, setMessage] = useState('')
  const roster = rosterOf(career)
  const ids = new Set(roster.map(player => player.id))
  const finances = financesOf(career)
  const contracts = contractsOf(career)
  const wages = wageUsed(career)
  const locked = !!career.match && career.match.cursor < 9
  function apply(next: Career, success: string, failure: string) { if (next === career) return setMessage(failure); onChange(next); setMessage(success) }
  return <div className="market-center">
    <section className="market-hero"><div><p className="eyebrow">CENTRAL DE NEGOCIAÇÕES</p><h2>Construa o seu elenco.</h2><p>Contrate dentro do orçamento, controle os salários e abra espaço vendendo reservas.</p></div><span aria-hidden="true">↗</span></section>
    <div className="finance-grid"><article><span>ORÇAMENTO</span><strong>{money(finances.budget)}</strong><small>Disponível para taxas e renovações</small></article><article><span>FOLHA SALARIAL</span><strong>R$ {wages} mil</strong><small>Limite mensal: R$ {finances.wageLimit} mil</small><div className="budget-bar"><span style={{ width: `${Math.min(100, wages / finances.wageLimit * 100)}%` }} /></div></article><article><span>ELENCO</span><strong>{roster.length} <small>/ 23</small></strong><small>Mínimo permitido para vendas: 16</small></article></div>
    {locked && <p className="info-banner">As negociações ficam pausadas enquanto uma partida está em andamento.</p>}
    {message && <p className="market-message" role="status">{message}</p>}
    <section className="panel"><div className="section-heading"><div><p className="eyebrow">ATLETAS OBSERVADOS</p><h2>Oportunidades do mercado</h2></div><span className="muted">Valores estimados pelo jogo · contrato de 3 temporadas</span></div><div className="transfer-grid">{marketPlayers.filter(player => !ids.has(player.id)).map(player => { const affordable = finances.budget >= player.value && wages + player.wage <= finances.wageLimit && roster.length < 23; return <article className="transfer-card" key={player.id}><div className="transfer-rating"><strong>{player.rating}</strong><span>{player.position}</span></div><div><h3>{player.name}</h3><p>{player.age} anos · salário R$ {player.wage} mil/mês</p><strong>{money(player.value)}</strong></div><button className="primary" disabled={locked || !affordable} onClick={() => apply(buyPlayer(career, player.id), `${player.name} assinou por três temporadas.`, 'A contratação ultrapassa o orçamento, a folha ou o limite de 23 atletas.')}>Contratar</button></article> })}</div>{marketPlayers.every(player => ids.has(player.id)) && <p className="empty-market">Todos os atletas observados já fazem parte do seu elenco.</p>}</section>
    <section className="panel market-roster"><div className="section-heading"><div><p className="eyebrow">GESTÃO DE CONTRATOS</p><h2>Seu elenco</h2></div><span className="muted">Titulares precisam ir ao banco antes de serem vendidos.</span></div><div className="table-wrap"><table><thead><tr><th>Atleta</th><th>Pos.</th><th>Nível</th><th>Contrato</th><th>Salário</th><th>Valor</th><th>Ação</th></tr></thead><tbody>{roster.map(player => { const contract = contracts[player.id] ?? { seasons: 2, wage: player.wage, value: player.value }; const starter = (career.lineup ?? defaultLineupFor(career.clubId)).includes(player.id); return <tr key={player.id}><td>{player.name}</td><td><span className="position">{player.position}</span></td><td><strong className="rating">{overall(career, player.id)}</strong></td><td>{contract.seasons} {contract.seasons === 1 ? 'temporada' : 'temporadas'}</td><td>R$ {contract.wage} mil</td><td>{money(contract.value)}</td><td>{contract.seasons === 1 ? <button className="table-action" disabled={locked} onClick={() => apply(renewContract(career, player.id), `Contrato de ${player.name} renovado por três temporadas.`, 'O orçamento não cobre a renovação.')}>Renovar</button> : <button className="table-action danger" disabled={locked || starter || roster.length <= 16} onClick={() => apply(sellPlayer(career, player.id), `${player.name} foi vendido.`, starter ? 'Coloque o atleta no banco antes de negociar.' : 'O elenco precisa manter pelo menos 16 atletas.')}>Vender</button>}</td></tr> })}</tbody></table></div></section>
    {!!career.transfers?.length && <section className="panel"><p className="eyebrow">HISTÓRICO RECENTE</p><h2>Movimentações</h2><div className="transfer-history">{career.transfers.slice(-6).reverse().map((record, index) => <p key={`${record.season}-${record.playerId}-${record.kind}-${index}`}><span>T{record.season}</span><strong>{record.kind === 'buy' ? 'Contratação' : record.kind === 'sell' ? 'Venda' : 'Renovação'} · {allPlayers.find(player => player.id === record.playerId)?.name}</strong><b>{money(record.amount)}</b></p>)}</div></section>}
    <details className="rules-explainer"><summary>Como funciona o mercado nesta versão?</summary><p>Contratações descontam o valor do orçamento e ocupam espaço na folha. Vendas rendem 85% do valor estimado. O elenco pode ter entre 16 e 23 atletas. Contratos novos duram três temporadas; a duração cai ao iniciar uma nova temporada. Atletas com um ano restante podem renovar por 10% do valor de mercado. Valores e salários são estimativas internas e serão equilibrados conforme o restante da economia for desenvolvido.</p></details>
  </div>
}
