import { useState } from 'react'
import { allPlayers, clubs, defaultLineupFor, rosterOf, type Career } from './model'
import { overall } from './progression'
import { contractsOf, financesOf, renewContract, wageUsed } from './transfers'
import { ageOf, clubOf } from './world'
import { assignMission, hireScout, knowledgeOf, potentialOf, scoutMarket, scoutingOf, toggleCompared, toggleFavorite } from './scouting'
import { listPlayer, startNegotiation } from './negotiations'
import { NegotiationPanel } from './NegotiationPanel'

const money = (value: number) => value >= 1000 ? `R$ ${(value / 1000).toFixed(1).replace('.', ',')} mi` : `R$ ${value} mil`
type Tab = 'search' | 'scouts' | 'deals' | 'roster'
export function Market({ career, onChange }: { career: Career; onChange: (career: Career) => void }) {
  const [tab, setTab] = useState<Tab>('search'); const [query, setQuery] = useState(''); const [position, setPosition] = useState('all'); const [maxAge, setMaxAge] = useState(40); const [maxValue, setMaxValue] = useState(50000); const [club, setClub] = useState('all'); const [favoritesOnly, setFavoritesOnly] = useState(false); const [message, setMessage] = useState('')
  const [missionScout, setMissionScout] = useState(''); const [missionPosition, setMissionPosition] = useState('all'); const [missionAge, setMissionAge] = useState(23)
  const roster = rosterOf(career); const ids = new Set(roster.map(player => player.id)); const scouting = scoutingOf(career); const locked = !!career.match && career.match.cursor < 9
  const active = allPlayers.filter(player => { const currentClub = clubOf(career, player.id); return currentClub && currentClub !== career.clubId && !ids.has(player.id) && player.name.toLocaleLowerCase('pt-BR').includes(query.toLocaleLowerCase('pt-BR')) && (position === 'all' || player.position === position) && ageOf(career, player.id) <= maxAge && player.value <= maxValue && (club === 'all' || currentClub === club) && (!favoritesOnly || scouting.favorites.includes(player.id)) }).sort((a, b) => b.rating - a.rating).slice(0, 60)
  const apply = (next: Career, success: string, failure: string) => { if (next === career) setMessage(failure); else { onChange(next); setMessage(success) } }
  const negotiate = (playerId: string, kind: 'purchase' | 'loan') => { const next = startNegotiation(career, playerId, kind); apply(next, 'Conversa aberta na mesa de negociações.', 'Já existe uma conversa ativa para este atleta.'); setTab('deals') }
  return <div className="market-center">
    <section className="market-hero"><div><p className="eyebrow">CENTRAL DE MERCADO</p><h2>Descubra. Negocie. Assine.</h2><p>Da observação ao contrato, cada decisão acontece em etapas claras.</p></div><span aria-hidden="true">⇄</span></section>
    <div className="market-tabs">{([['search', 'Pesquisar atletas'], ['scouts', 'Olheiros'], ['deals', 'Negociações'], ['roster', 'Meu elenco']] as [Tab, string][]).map(([id, label]) => <button className={tab === id ? 'active' : ''} key={id} onClick={() => setTab(id)}>{label}</button>)}</div>
    {message && <p className="market-message" role="status">{message}</p>}{locked && <p className="info-banner">Decisões financeiras ficam pausadas durante a partida.</p>}
    {tab === 'search' && <Search career={career} active={active} scouting={scouting} query={query} position={position} maxAge={maxAge} maxValue={maxValue} club={club} favoritesOnly={favoritesOnly} locked={locked} onQuery={setQuery} onPosition={setPosition} onMaxAge={setMaxAge} onMaxValue={setMaxValue} onClub={setClub} onFavoritesOnly={setFavoritesOnly} onChange={onChange} onNegotiate={negotiate} />}
    {tab === 'scouts' && <Scouts career={career} scouting={scouting} missionScout={missionScout} missionPosition={missionPosition} missionAge={missionAge} onScout={setMissionScout} onPosition={setMissionPosition} onAge={setMissionAge} onApply={apply} />}
    {tab === 'deals' && <NegotiationPanel career={career} onChange={onChange} />}
    {tab === 'roster' && <Roster career={career} locked={locked} onChange={onChange} onDeals={() => setTab('deals')} onMessage={setMessage} />}
    <details className="rules-explainer"><summary>Como funciona o mercado completo?</summary><p>Relatórios completos liberam compra e empréstimo. Você define taxa, parcelas, bônus e cláusulas; o clube pode aceitar, rejeitar ou contrapropor. Depois vêm salário, duração, luvas e papel no elenco. Nas saídas, coloque o atleta na lista, receba uma oferta e confirme apenas após revisar tudo.</p></details>
  </div>
}

function Search({ career, active, scouting, query, position, maxAge, maxValue, club, favoritesOnly, locked, onQuery, onPosition, onMaxAge, onMaxValue, onClub, onFavoritesOnly, onChange, onNegotiate }: any) {
  const compared = scouting.compared.map((id: string) => allPlayers.find(player => player.id === id)).filter(Boolean)
  return <><section className="scout-filters"><label>Nome<input value={query} onChange={event => onQuery(event.target.value)} placeholder="Buscar atleta" /></label><label>Posição<select value={position} onChange={event => onPosition(event.target.value)}><option value="all">Todas</option>{[...new Set(allPlayers.map(player => player.position))].map(value => <option key={value}>{value}</option>)}</select></label><label>Idade máxima<input type="number" min="16" max="40" value={maxAge} onChange={event => onMaxAge(Number(event.target.value))} /></label><label>Valor máximo<input type="number" min="500" step="500" value={maxValue} onChange={event => onMaxValue(Number(event.target.value))} /></label><label>Clube<select value={club} onChange={event => onClub(event.target.value)}><option value="all">Todos</option>{clubs.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><button className={favoritesOnly ? 'filter-favorite active' : 'filter-favorite'} onClick={() => onFavoritesOnly(!favoritesOnly)}>★ Favoritos</button></section><div className="search-count"><strong>{active.length}</strong> encontrados <span>{scouting.favorites.length} favoritos · {scouting.compared.length}/3 comparados</span></div>
    {!!compared.length && <section className="comparison-dock"><div className="section-heading"><h2>Comparação</h2><span>Até três jogadores</span></div><div>{compared.map((player: any) => { const knowledge = knowledgeOf(career, player.id); return <article key={player.id}><button onClick={() => onChange(toggleCompared(career, player.id))}>×</button><strong>{player.name}</strong><span>{player.position} · {ageOf(career, player.id)} anos</span><b>{knowledge >= 2 ? `GER ${player.rating}` : 'GER ?'}</b><small>{knowledge >= 3 ? `POT ${potentialOf(career, player.id)} · ${money(player.value)}` : `Relatório ${knowledge}/3`}</small></article> })}</div></section>}
    <section className="player-search-results">{active.map((player: any) => { const knowledge = knowledgeOf(career, player.id); const favorite = scouting.favorites.includes(player.id); const comparing = scouting.compared.includes(player.id); return <article key={player.id}><div className="scout-rating"><strong>{knowledge >= 2 ? player.rating : '?'}</strong><span>{player.position}</span></div><div><h3>{player.name}</h3><p>{ageOf(career, player.id)} anos · {clubs.find(item => item.id === clubOf(career, player.id))?.name}</p><div className="knowledge-track"><span style={{ width: `${knowledge / 3 * 100}%` }} /></div><small>{knowledge === 0 ? 'Sem relatório' : knowledge === 1 ? 'Perfil inicial' : knowledge === 2 ? `Nível confirmado · ${money(Math.round(player.value * .8))}–${money(Math.round(player.value * 1.2))}` : `POT ${potentialOf(career, player.id)} · ${money(player.value)} · salário R$ ${player.wage} mil`}</small></div><div className="scout-actions"><button className={favorite ? 'active' : ''} onClick={() => onChange(toggleFavorite(career, player.id))}>{favorite ? '★ Salvo' : '☆ Favoritar'}</button><button className={comparing ? 'active' : ''} onClick={() => onChange(toggleCompared(career, player.id))}>Comparar</button><button className="primary" disabled={knowledge < 3 || locked} onClick={() => onNegotiate(player.id, 'purchase')}>Comprar</button><button disabled={knowledge < 3 || locked} onClick={() => onNegotiate(player.id, 'loan')}>Empréstimo</button></div></article> })}</section></>
}

function Scouts({ career, scouting, missionScout, missionPosition, missionAge, onScout, onPosition, onAge, onApply }: any) {
  return <><section className="scout-overview"><article><span>OLHEIROS</span><strong>{scouting.hired.length}/3</strong></article><article><span>MISSÕES</span><strong>{scouting.missions.length}</strong></article><article><span>CUSTO MENSAL</span><strong>R$ {scouting.hired.reduce((sum: number, scout: any) => sum + scout.wage, 0)} mil</strong></article></section><section className="scout-market-grid">{scoutMarket.map(scout => { const hired = scouting.hired.some((item: any) => item.id === scout.id); return <article className={hired ? 'hired' : ''} key={scout.id}><span className="scout-quality">{scout.quality}</span><h3>{scout.name}</h3><p>{scout.specialty} · {scout.region}</p><small>R$ {scout.wage} mil/mês</small><button className="secondary" disabled={hired || scouting.hired.length >= 3} onClick={() => onApply(hireScout(career, scout.id), 'Olheiro contratado.', 'Limite atingido.')}>{hired ? 'Contratado ✓' : 'Contratar'}</button></article> })}</section>{!!scouting.hired.length && <section className="panel mission-builder"><h2>Nova missão</h2><div><label>Olheiro<select value={missionScout} onChange={event => onScout(event.target.value)}><option value="">Escolha</option>{scouting.hired.map((scout: any) => <option key={scout.id} value={scout.id}>{scout.name}</option>)}</select></label><label>Posição<select value={missionPosition} onChange={event => onPosition(event.target.value)}><option value="all">Todas</option>{[...new Set(allPlayers.map(player => player.position))].map(value => <option key={value}>{value}</option>)}</select></label><label>Idade máxima<input type="number" min="16" max="40" value={missionAge} onChange={event => onAge(Number(event.target.value))} /></label></div><button className="primary" disabled={!missionScout} onClick={() => onApply(assignMission(career, missionScout, missionPosition, missionAge, 'Brasil'), 'Missão iniciada.', 'Escolha um olheiro.')}>Iniciar missão</button></section>}<section className="mission-list">{scouting.missions.map((mission: any) => <article key={mission.id}><strong>{scouting.hired.find((scout: any) => scout.id === mission.scoutId)?.name}</strong><span>{mission.position} · até {mission.maxAge} anos</span><progress max="3" value={Math.min(3, Math.floor(((career.day ?? 1) - mission.startedDay) / 2))} /></article>)}</section></>
}

function Roster({ career, locked, onChange, onDeals, onMessage }: { career: Career; locked: boolean; onChange: (career: Career) => void; onDeals: () => void; onMessage: (message: string) => void }) {
  const roster = rosterOf(career); const contracts = contractsOf(career); const finances = financesOf(career)
  const offer = (playerId: string, kind: 'sale' | 'loan') => { let next = listPlayer(career, playerId, kind); next = startNegotiation(next, playerId, kind); onChange(next); onMessage('Atleta listado. Uma oferta chegou à mesa de negociações.'); onDeals() }
  return <section className="panel market-roster"><div className="finance-grid"><article><span>ORÇAMENTO</span><strong>{money(finances.budget)}</strong></article><article><span>FOLHA</span><strong>R$ {wageUsed(career)} mil</strong><small>Limite R$ {finances.wageLimit} mil</small></article><article><span>ELENCO</span><strong>{roster.length}/23</strong></article></div><div className="table-wrap"><table><thead><tr><th>Atleta</th><th>Pos.</th><th>GER</th><th>Contrato</th><th>Valor</th><th>Decisão</th></tr></thead><tbody>{roster.map(player => { const contract = contracts[player.id]; const starter = (career.lineup ?? defaultLineupFor(career.clubId)).includes(player.id); return <tr key={player.id}><td>{player.name}</td><td>{player.position}</td><td>{overall(career, player.id)}</td><td>{contract?.seasons ?? 2} temp.</td><td>{money(contract?.value ?? player.value)}</td><td><button className="table-action danger" disabled={locked || starter || roster.length <= 16} onClick={() => offer(player.id, 'sale')}>Listar venda</button><button className="table-action" disabled={locked || starter} onClick={() => offer(player.id, 'loan')}>Listar empréstimo</button>{contract?.seasons === 1 && <button className="table-action" onClick={() => onChange(renewContract(career, player.id))}>Renovar</button>}</td></tr> })}</tbody></table></div></section>
}

