import { useState } from 'react'
import { allPlayers, clubs, defaultLineupFor, rosterOf, type Career } from './model'
import { overall } from './progression'
import { contractsOf, financesOf, renewContract, sellPlayer, wageUsed } from './transfers'
import { ageOf, clubOf } from './world'
import { assignMission, hireScout, knowledgeOf, potentialOf, scoutMarket, scoutingOf, toggleCompared, toggleFavorite } from './scouting'

const money = (value: number) => value >= 1000 ? `R$ ${(value / 1000).toFixed(1).replace('.', ',')} mi` : `R$ ${value} mil`
type Tab = 'search' | 'scouts' | 'roster'
export function Market({ career, onChange }: { career: Career; onChange: (career: Career) => void }) {
  const [tab, setTab] = useState<Tab>('search'); const [query, setQuery] = useState(''); const [position, setPosition] = useState('all'); const [maxAge, setMaxAge] = useState(40); const [maxValue, setMaxValue] = useState(50000); const [club, setClub] = useState('all'); const [favoritesOnly, setFavoritesOnly] = useState(false); const [message, setMessage] = useState('')
  const [missionScout, setMissionScout] = useState(''); const [missionPosition, setMissionPosition] = useState('all'); const [missionAge, setMissionAge] = useState(23); const [missionRegion, setMissionRegion] = useState('Brasil')
  const roster = rosterOf(career); const ids = new Set(roster.map(player => player.id)); const finances = financesOf(career); const contracts = contractsOf(career); const scouting = scoutingOf(career); const locked = !!career.match && career.match.cursor < 9
  const active = allPlayers.filter(player => { const currentClub = clubOf(career, player.id); return currentClub && currentClub !== career.clubId && !ids.has(player.id) && player.name.toLocaleLowerCase('pt-BR').includes(query.toLocaleLowerCase('pt-BR')) && (position === 'all' || player.position === position) && ageOf(career, player.id) <= maxAge && player.value <= maxValue && (club === 'all' || currentClub === club) && (!favoritesOnly || scouting.favorites.includes(player.id)) }).sort((a, b) => b.rating - a.rating).slice(0, 60)
  function apply(next: Career, success: string, failure: string) { if (next === career) return setMessage(failure); onChange(next); setMessage(success) }
  const compared = scouting.compared.map(id => allPlayers.find(player => player.id === id)).filter(Boolean)
  return <div className="market-center"><section className="market-hero"><div><p className="eyebrow">REDE DE RECRUTAMENTO</p><h2>Conhecimento antes da proposta.</h2><p>Pesquise o futebol brasileiro, monte sua lista e envie olheiros para reduzir a incerteza.</p></div><span aria-hidden="true">⌕</span></section>
    <div className="market-tabs">{([['search', 'Pesquisar atletas'], ['scouts', 'Olheiros e missões'], ['roster', 'Meu elenco']] as [Tab, string][]).map(([id, label]) => <button className={tab === id ? 'active' : ''} key={id} onClick={() => setTab(id)}>{label}</button>)}</div>
    {message && <p className="market-message" role="status">{message}</p>}{locked && <p className="info-banner">A rede pode ser consultada, mas decisões ficam pausadas durante a partida.</p>}
    {tab === 'search' && <><section className="scout-filters"><label>Buscar por nome<input value={query} onChange={event => setQuery(event.target.value)} placeholder="Digite o nome do atleta" /></label><label>Posição<select value={position} onChange={event => setPosition(event.target.value)}><option value="all">Todas</option>{[...new Set(allPlayers.map(player => player.position))].map(value => <option key={value}>{value}</option>)}</select></label><label>Idade máxima<input type="number" min="16" max="40" value={maxAge} onChange={event => setMaxAge(Number(event.target.value))} /></label><label>Valor máximo<input type="number" min="500" step="500" value={maxValue} onChange={event => setMaxValue(Number(event.target.value))} /></label><label>Clube<select value={club} onChange={event => setClub(event.target.value)}><option value="all">Todos</option>{clubs.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><button className={favoritesOnly ? 'filter-favorite active' : 'filter-favorite'} onClick={() => setFavoritesOnly(value => !value)}>★ Só favoritos</button></section><div className="search-count"><strong>{active.length}</strong> atletas encontrados <span>· {scouting.favorites.length} favoritos · comparação {scouting.compared.length}/3</span></div>
      {!!compared.length && <section className="comparison-dock"><div className="section-heading"><h2>Comparação</h2><span>Até três atletas</span></div><div>{compared.map(player => { if (!player) return null; const knowledge = knowledgeOf(career, player.id); return <article key={player.id}><button aria-label="Remover da comparação" onClick={() => onChange(toggleCompared(career, player.id))}>×</button><strong>{player.name}</strong><span>{player.position} · {ageOf(career, player.id)} anos</span><b>{knowledge >= 2 ? `GER ${player.rating}` : 'GER ?'}</b><small>{knowledge >= 3 ? `Potencial ${potentialOf(career, player.id)} · ${money(player.value)}` : `Relatório ${knowledge}/3`}</small></article> })}</div></section>}
      <section className="player-search-results">{active.map(player => { const knowledge = knowledgeOf(career, player.id); const currentClub = clubs.find(item => item.id === clubOf(career, player.id)); const favorite = scouting.favorites.includes(player.id); const comparing = scouting.compared.includes(player.id); return <article key={player.id}><div className="scout-rating"><strong>{knowledge >= 2 ? player.rating : '?'}</strong><span>{player.position}</span></div><div><h3>{player.name}</h3><p>{ageOf(career, player.id)} anos · {currentClub?.name}</p><div className="knowledge-track"><span style={{ width: `${knowledge / 3 * 100}%` }} /></div><small>{knowledge === 0 ? 'Sem relatório' : knowledge === 1 ? 'Perfil inicial revelado' : knowledge === 2 ? `Nível confirmado · valor entre ${money(Math.round(player.value * .8))} e ${money(Math.round(player.value * 1.2))}` : `Relatório completo · POT ${potentialOf(career, player.id)} · ${money(player.value)} · R$ ${player.wage} mil/mês`}</small></div><div className="scout-actions"><button className={favorite ? 'active' : ''} onClick={() => onChange(toggleFavorite(career, player.id))}>{favorite ? '★ Favorito' : '☆ Favoritar'}</button><button className={comparing ? 'active' : ''} onClick={() => onChange(toggleCompared(career, player.id))}>{comparing ? 'Comparando ✓' : 'Comparar'}</button><button className="primary" disabled={knowledge < 3} onClick={() => setMessage('Relatório concluído. A negociação detalhada será aberta na Edição 20.')}>Abrir relatório</button></div></article> })}{!active.length && <p className="empty-market">Nenhum atleta corresponde aos filtros atuais.</p>}</section></>}
    {tab === 'scouts' && <><section className="scout-overview"><article><span>OLHEIROS</span><strong>{scouting.hired.length}/3</strong></article><article><span>MISSÕES ATIVAS</span><strong>{scouting.missions.length}</strong></article><article><span>CUSTO MENSAL</span><strong>R$ {scouting.hired.reduce((sum, scout) => sum + scout.wage, 0)} mil</strong></article></section><section className="panel"><div className="section-heading"><div><p className="eyebrow">EQUIPE DE OBSERVAÇÃO</p><h2>Contrate especialistas</h2></div><span>Qualidade maior acelera os relatórios.</span></div><div className="scout-market-grid">{scoutMarket.map(scout => { const hired = scouting.hired.some(item => item.id === scout.id); return <article className={hired ? 'hired' : ''} key={scout.id}><span className="scout-quality">{scout.quality}</span><h3>{scout.name}</h3><p>{scout.specialty} · {scout.region}</p><small>R$ {scout.wage} mil/mês</small><button className="secondary" disabled={hired || scouting.hired.length >= 3} onClick={() => apply(hireScout(career, scout.id), `${scout.name} entrou para a equipe.`, 'O limite de três olheiros foi atingido.')}>{hired ? 'Contratado ✓' : 'Contratar olheiro'}</button></article> })}</div></section>
      <section className="panel mission-builder"><p className="eyebrow">NOVA MISSÃO</p><h2>Defina o perfil procurado</h2>{!scouting.hired.length ? <p className="muted">Contrate um olheiro para criar sua primeira missão.</p> : <><div><label>Responsável<select value={missionScout} onChange={event => setMissionScout(event.target.value)}><option value="">Escolha</option>{scouting.hired.map(scout => <option key={scout.id} value={scout.id}>{scout.name}</option>)}</select></label><label>Posição<select value={missionPosition} onChange={event => setMissionPosition(event.target.value)}><option value="all">Todas</option>{[...new Set(allPlayers.map(player => player.position))].map(value => <option key={value}>{value}</option>)}</select></label><label>Idade máxima<input type="number" min="16" max="40" value={missionAge} onChange={event => setMissionAge(Number(event.target.value))} /></label><label>Região<select value={missionRegion} onChange={event => setMissionRegion(event.target.value)}><option>Brasil</option><option>América do Sul</option><option>Mundo</option></select></label></div><button className="primary" disabled={!missionScout} onClick={() => apply(assignMission(career, missionScout, missionPosition, missionAge, missionRegion), 'Missão iniciada. Avance os dias para aprofundar os relatórios.', 'Escolha um olheiro responsável.')}>Iniciar missão →</button></>}</section><section className="mission-list">{scouting.missions.map(mission => { const scout = scouting.hired.find(item => item.id === mission.scoutId); const cycles = Math.max(0, Math.floor(((career.day ?? 1) - mission.startedDay) / 2)); return <article key={mission.id}><strong>{scout?.name}</strong><span>{mission.position === 'all' ? 'Todas as posições' : mission.position} · até {mission.maxAge} anos</span><progress max="3" value={Math.min(3, cycles + ((scout?.quality ?? 0) >= 85 ? 1 : 0))} /><small>{cycles >= 3 ? 'Relatórios completos' : `Ciclo ${Math.min(3, cycles)}/3 · avance o calendário`}</small></article> })}</section></>}
    {tab === 'roster' && <section className="panel market-roster"><div className="finance-grid"><article><span>ORÇAMENTO</span><strong>{money(finances.budget)}</strong></article><article><span>FOLHA</span><strong>R$ {wageUsed(career)} mil</strong><small>Limite R$ {finances.wageLimit} mil</small></article><article><span>ELENCO</span><strong>{roster.length}/23</strong></article></div><div className="section-heading"><h2>Contratos do elenco</h2><span className="muted">As negociações completas chegam na Edição 20.</span></div><div className="table-wrap"><table><thead><tr><th>Atleta</th><th>Pos.</th><th>Nível</th><th>Contrato</th><th>Salário</th><th>Valor</th><th>Ação atual</th></tr></thead><tbody>{roster.map(player => { const contract = contracts[player.id] ?? { seasons: 2, wage: player.wage, value: player.value }; const starter = (career.lineup ?? defaultLineupFor(career.clubId)).includes(player.id); return <tr key={player.id}><td>{player.name}</td><td>{player.position}</td><td>{overall(career, player.id)}</td><td>{contract.seasons} temp.</td><td>R$ {contract.wage} mil</td><td>{money(contract.value)}</td><td>{contract.seasons === 1 ? <button className="table-action" disabled={locked} onClick={() => apply(renewContract(career, player.id), 'Contrato renovado.', 'Orçamento insuficiente.')}>Renovar</button> : <button className="table-action danger" disabled={locked || starter || roster.length <= 16} onClick={() => apply(sellPlayer(career, player.id), 'Atleta vendido.', 'Coloque-o no banco e mantenha 16 atletas.')}>Vender</button>}</td></tr> })}</tbody></table></div></section>}
    <details className="rules-explainer"><summary>Como os relatórios evoluem?</summary><p>A busca mostra todos os atletas ativos, mas os dados esportivos e financeiros começam ocultos. Uma missão compatível avança a cada dois dias: primeiro revela o perfil, depois confirma o nível e a faixa de valor, e por fim mostra potencial, valor e salário. Olheiros de elite começam um nível à frente. Favoritos e comparação permanecem salvos.</p></details></div>
}

