import { useState } from 'react'
import { allPlayers, clubs, type Career } from './model'
import { acceptCounter, changeTerms, completeNegotiation, deskOf, generateListedOffers, openPersonalTerms, submitClubOffer, withdrawNegotiation } from './negotiations'
import type { Negotiation, NegotiationTerms } from './types'

const money = (value: number) => value >= 1000 ? `R$ ${(value / 1000).toFixed(1).replace('.', ',')} mi` : `R$ ${value} mil`
const statusLabel = { draft: 'Preparando proposta', 'club-review': 'Em análise', countered: 'Contraproposta', 'club-accepted': 'Acordo entre clubes', 'personal-terms': 'Termos pessoais', completed: 'Concluída', rejected: 'Rejeitada', withdrawn: 'Encerrada' }
export function NegotiationPanel({ career, onChange }: { career: Career; onChange: (career: Career) => void }) {
  const deals = deskOf(career).negotiations; const [selectedId, setSelectedId] = useState(deals.at(-1)?.id ?? ''); const deal = deals.find(item => item.id === selectedId) ?? deals.at(-1)
  return <section className="negotiation-center"><div className="negotiation-list"><div className="section-heading"><div><p className="eyebrow">MESA DE NEGOCIAÇÕES</p><h2>Conversas em andamento</h2></div><button className="secondary" onClick={() => onChange(generateListedOffers(career))}>Buscar ofertas por listados</button></div>{deals.slice().reverse().map(item => <button className={deal?.id === item.id ? 'active' : ''} key={item.id} onClick={() => setSelectedId(item.id)}><strong>{allPlayers.find(player => player.id === item.playerId)?.name}</strong><span>{item.kind === 'purchase' ? 'Compra' : item.kind === 'loan' ? 'Empréstimo' : 'Venda'} · {statusLabel[item.status]}</span><b>{money(item.terms.fee)}</b></button>)}{!deals.length && <p className="empty-market">Nenhuma conversa aberta. Conclua um relatório ou coloque um atleta na lista.</p>}</div>{deal && <DealEditor career={career} deal={deal} onChange={onChange} />}</section>
}
function NumberField({ label, value, min = 0, max = 100000, step = 1, onChange }: { label: string; value: number; min?: number; max?: number; step?: number; onChange: (value: number) => void }) { return <label>{label}<input type="number" min={min} max={max} step={step} value={value} onChange={event => onChange(Number(event.target.value))} /></label> }
function DealEditor({ career, deal, onChange }: { career: Career; deal: Negotiation; onChange: (career: Career) => void }) {
  const player = allPlayers.find(item => item.id === deal.playerId)!; const editable = ['draft', 'countered', 'personal-terms'].includes(deal.status)
  const set = (part: Partial<NegotiationTerms>) => onChange(changeTerms(career, deal.id, { ...deal.terms, ...part }))
  return <section className="deal-editor"><header><div><p className="eyebrow">{deal.kind === 'purchase' ? 'COMPRA DEFINITIVA' : deal.kind === 'loan' ? 'EMPRÉSTIMO' : 'PROPOSTA DE SAÍDA'}</p><h2>{player.name}</h2><span>{clubs.find(club => club.id === deal.fromClubId)?.name} → {clubs.find(club => club.id === deal.toClubId)?.name}</span></div><span className={`deal-status ${deal.status}`}>{statusLabel[deal.status]}</span></header><div className="deal-steps"><span className={deal.round >= 0 ? 'done' : ''}>1 Estrutura</span><span className={['club-accepted', 'personal-terms', 'completed'].includes(deal.status) ? 'done' : ''}>2 Clube</span><span className={['personal-terms', 'completed'].includes(deal.status) ? 'done' : ''}>3 Atleta</span><span className={deal.status === 'completed' ? 'done' : ''}>4 Registro</span></div><p className="deal-note">{deal.note}</p>
    <div className="terms-grid"><NumberField label="Taxa principal" value={deal.terms.fee} step={100} onChange={fee => set({ fee })} /><NumberField label="Parcelas" value={deal.terms.installments} min={1} max={4} onChange={installments => set({ installments })} />{deal.kind === 'purchase' && <><NumberField label="Bônus por desempenho" value={deal.terms.performanceBonus} step={100} onChange={performanceBonus => set({ performanceBonus })} /><NumberField label="Venda futura (%)" value={deal.terms.sellOnPercent} max={30} onChange={sellOnPercent => set({ sellOnPercent })} /></>}{deal.kind === 'loan' && <><NumberField label="Duração (temporadas)" value={deal.terms.loanSeasons ?? 1} min={1} max={2} onChange={loanSeasons => set({ loanSeasons })} /><NumberField label="Salário pago (%)" value={deal.terms.wageShare ?? 60} max={100} onChange={wageShare => set({ wageShare })} /><NumberField label="Opção de compra" value={deal.terms.purchaseOption ?? player.value} step={100} onChange={purchaseOption => set({ purchaseOption })} /></>}{deal.status === 'personal-terms' && deal.kind !== 'sale' && <><NumberField label="Salário mensal" value={deal.terms.wage ?? player.wage} step={5} onChange={wage => set({ wage })} /><NumberField label="Duração do contrato" value={deal.terms.contractSeasons ?? 3} min={1} max={5} onChange={contractSeasons => set({ contractSeasons })} /><NumberField label="Luvas" value={deal.terms.signingBonus ?? 0} step={100} onChange={signingBonus => set({ signingBonus })} /><label>Papel no elenco<select value={deal.terms.squadRole} onChange={event => set({ squadRole: event.target.value as NegotiationTerms['squadRole'] })}><option value="prospect">Promessa</option><option value="rotation">Rotação</option><option value="starter">Titular</option><option value="key">Peça-chave</option></select></label></>}</div>
    {deal.counterTerms && deal.status === 'countered' && <div className="counter-card"><strong>Contraproposta do clube</strong><span>Taxa {money(deal.counterTerms.fee)} · {deal.counterTerms.installments} parcela(s)</span></div>}
    <div className="deal-actions">{['draft', 'countered'].includes(deal.status) && <button className="primary" disabled={!editable} onClick={() => onChange(submitClubOffer(career, deal.id))}>Enviar proposta</button>}{deal.status === 'countered' && <button className="secondary" onClick={() => onChange(acceptCounter(career, deal.id))}>Aceitar contraproposta</button>}{deal.status === 'club-accepted' && <button className="primary" onClick={() => onChange(openPersonalTerms(career, deal.id))}>{deal.kind === 'sale' ? 'Revisar e decidir' : 'Negociar com atleta'}</button>}{deal.status === 'personal-terms' && <button className="primary" onClick={() => onChange(completeNegotiation(career, deal.id))}>Confirmar e concluir</button>}{!['completed', 'rejected', 'withdrawn'].includes(deal.status) && <button className="text-button" onClick={() => onChange(withdrawNegotiation(career, deal.id))}>Encerrar conversa</button>}</div>
  </section>
}

