import { clubs, type Career } from './model'
import { advanceDay, averageEnergy, isMatchDay, preparation, sessions, train } from './season'
import { score, player } from './football'
import { fixtureDays, leagueDays } from './types'
export function Schedule({ career, onChange, onMatch, onLeague }: { career: Career; onChange: (c: Career) => void; onMatch: () => void; onLeague: () => void }) {
  const day = career.day ?? 1
  const active = career.leagueActive
  const calendar = active ? leagueDays : fixtureDays
  const days = active ? Array.from({ length: 17 }, (_, i) => i + 8) : Array.from({ length: 7 }, (_, i) => i + 1)
  const prep = preparation(career)
  const today = prep.sessions.find(s => s.day === day)
  return <section className="season-hub"><div className="season-stats"><article><span>ENERGIA DO ELENCO</span><strong>{averageEnergy(career)}%</strong></article><article><span>TÉCNICA</span><strong>+{prep.skill}<small> / 3</small></strong></article><article><span>PREPARO FÍSICO</span><strong>{prep.fitness}<small> / 3</small></strong></article><article><span>ENTROSAMENTO</span><strong>+{prep.cohesion}<small> / 6</small></strong></article></div>
    <div className="week-strip" aria-label="Calendário de pré-temporada">{days.map(d => <div key={d} className={d === day ? 'current-day' : d < day ? 'past-day' : ''} aria-current={d === day ? 'date' : undefined}><small>DIA {String(d).padStart(2, '0')}</small><strong>{calendar.includes(d) ? active ? 'Liga' : 'Amistoso' : 'Preparação'}</strong><span>{d < day ? 'Concluído' : d === day ? 'Hoje' : 'A seguir'}</span></div>)}</div>
    {day > (active ? 24 : 7) ? <section className="panel season-complete"><p className="eyebrow">{active ? 'LIGA CONCLUÍDA' : 'PRÉ-TEMPORADA CONCLUÍDA'}</p><h2>{active ? 'Uma campanha para recordar.' : 'Sete dias. Um time em evolução.'}</h2><p>{active ? 'Confira a classificação final e o objetivo da diretoria.' : 'Você completou os três amistosos. Sua primeira competição oficial está liberada.'}</p><button className="primary" onClick={onLeague}>{active ? 'Relatório e próxima temporada →' : 'Conhecer a Liga VT27 →'}</button></section> : isMatchDay(career) ? <section className="panel training-today"><div><p className="eyebrow">DIA DE JOGO</p><h2>Hoje o trabalho é no campo.</h2><p>Não há treino no dia de jogo. Conclua a partida e avance pelo pós-jogo.</p></div><button className="primary" onClick={onMatch}>{career.match ? 'Abrir partida' : 'Preparar a partida'} →</button></section> : <><section className="training-intro"><p className="eyebrow">PLANO DO DIA {day}</p><h2>{today ? 'Trabalho do dia concluído.' : 'Do que seu elenco precisa hoje?'}</h2><p>{today ? `Você escolheu ${sessions.find(s => s.kind === today.kind)?.name.toLowerCase()}. Os efeitos já foram aplicados e salvos.` : 'Uma atividade por dia para todo o elenco. Compare os efeitos antes de confirmar sua escolha.'}</p></section><div className="training-grid">{sessions.map(s => <article className={today?.kind === s.kind ? 'training-card completed' : 'training-card'} key={s.kind}><p className="eyebrow">{s.subtitle}</p><h3>{s.name}</h3><p>{s.effect}</p><button className={today?.kind === s.kind ? 'secondary' : 'primary'} disabled={!!today} onClick={() => onChange(train(career, s.kind))}>{today?.kind === s.kind ? 'Concluído hoje ✓' : 'Escolher ' + s.name.toLowerCase()}</button></article>)}</div>{today && <div className="next-day"><p>Ao avançar, todos recuperam mais 8 de energia pela noite de descanso, até 100.</p><button className="primary" onClick={() => onChange(advanceDay(career))}>Avançar para o dia {day + 1} →</button></div>}</>}
    <details className="rules-explainer"><summary>Como energia e preparação afetam o jogo?</summary><p>O nível técnico aumenta o nível efetivo dos atletas. O entrosamento soma força ao time. A energia reduz o desempenho gradualmente: 100% mantém a força; 0% aplica uma redução de 30%. O desgaste considera os minutos disputados e o preparo físico. Todos recuperam 8 ao avançar o dia.</p><p>Lesões e suspensões são medidas em partidas do clube. Uma ausência é cumprida quando o time conclui o próximo jogo, mesmo que o atleta não esteja relacionado.</p></details>
    <section className="panel history-panel"><p className="eyebrow">HISTÓRICO DE PARTIDAS</p>{!career.history?.length && <p className="muted">Os resultados aparecem aqui quando você avança após o jogo.</p>}{career.history?.map(h => { const result = score(h.match); return <details key={h.day} className="history-result"><summary><span>Dia {h.day} · {clubs.find(c => c.id === career.clubId)?.name} × {clubs.find(c => c.id === h.match.opponent)?.name}</span><strong>{result.home} : {result.away}</strong></summary><p>{h.match.formation} · Força na partida: {h.match.strength}</p><div className="player-ratings">{h.match.ratings.map(r => <div key={r.playerId}><span>{player(r.playerId).name}</span><strong>{r.value.toFixed(1)}</strong></div>)}</div></details> })}</section>
  </section>
}
