import { useState } from 'react'
import { clubs, type Career } from './model'
import { canRenew, playerStats, renewSeason } from './progression'
import { boardTarget, standings } from './league'
export function SeasonReview({ career, onChange, onCalendar }: { career: Career; onChange: (c: Career) => void; onCalendar: () => void }) {
  const [confirm, setConfirm] = useState(false)
  const stats = playerStats(career)
  const table = standings(career.leagueResults ?? [])
  const own = table.find(row => row.id === career.clubId)!
  const rank = table.findIndex(row => row.id === career.clubId) + 1
  const done = canRenew(career)
  const target = boardTarget(career.clubId)
  const goals = stats.reduce((sum, p) => sum + p.goals, 0)
  return <section className="review-hub"><div className="league-hero"><div><p className="eyebrow">SUA TRAJETÓRIA · TEMPORADA {career.seasonNumber ?? 1}</p><h2>Uma história que continua.</h2><p>{done ? 'A campanha terminou. Veja o que seu time conquistou.' : 'Acompanhe o desempenho dos seus atletas ao longo da liga.'}</p></div><span className="league-emblem" aria-hidden="true">↗</span></div>
    <div className="league-summary"><article><span>CAMPANHA NA LIGA</span><strong>{own.points} pontos</strong><small>{own.played}/6 jogos · {own.wins} vitórias · {own.draws} empates · {own.losses} derrotas</small></article><article><span>POSIÇÃO {done ? 'FINAL' : 'ATUAL'}</span><strong>{own.played ? rank + 'º' : '—'}</strong><small>{goals} gols marcados pelo seu time</small></article><article><span>AVALIAÇÃO DA DIRETORIA</span><strong>{done ? rank <= target ? 'Meta alcançada' : 'Abaixo da meta' : 'Em acompanhamento'}</strong><small>{target === 1 ? 'Objetivo: ser campeão' : 'Objetivo: terminar no top ' + target}. {done ? 'O projeto continua com você no comando.' : 'A avaliação final acontece ao concluir a temporada.'}</small></article></div>
    <section className="panel"><div className="section-heading"><h2>Evolução do elenco</h2><span className="muted">Somente partidas oficiais · Temporada atual</span></div><div className="table-wrap"><table><caption className="sr-only">Desempenho individual e evolução prevista</caption><thead><tr><th scope="col">Atleta</th><th scope="col">Nível</th><th scope="col">Jogos</th><th scope="col">Gols</th><th scope="col">Nota média</th><th scope="col">Próxima temporada</th></tr></thead><tbody>{stats.map(p => <tr key={p.id}><th scope="row">{p.name}<small className="stat-position">{p.position}</small></th><td>{p.rating}</td><td>{p.appearances}</td><td>{p.goals}</td><td>{p.average === null ? '—' : p.average.toFixed(2)}</td><td><span className={p.gain ? 'growth-badge' : 'muted'}>{p.gain ? '+' + p.gain + ' nível' : p.growth === 10 ? 'Limite atingido' : 'Sem ganho previsto'}</span></td></tr>)}</tbody></table></div><details className="rules-explainer"><summary>Como os jogadores evoluem?</summary><p>Disputar pelo menos 3 partidas oficiais como titular dá +1 de nível ao concluir a temporada. Com nota média igual ou superior a 7,50, o ganho é +2. O limite acumulado é +10 por atleta. Amistosos não contam. Os ganhos são aplicados uma única vez, ao iniciar a próxima temporada; durante a liga, esta coluna é uma previsão.</p><p>O nível individual é permanente e influencia a força do time. O bônus de treino técnico é coletivo e temporário. Idade, lesões e aposentadorias ainda não são simuladas.</p></details></section>
    <section className="next-day review-next"><div><h2>{done ? 'Pronto para escrever o próximo capítulo?' : 'Conclua a campanha para seguir em frente.'}</h2><p>{done ? 'A temporada atual será arquivada com resultados, notas e evolução. A próxima começa no dia 1, com energia cheia e nova pré-temporada.' : 'Termine as seis rodadas e avance após a última partida. Você mantém sua carreira e o mesmo clube.'}</p></div>{done ? <button className="primary" onClick={() => setConfirm(true)}>Preparar temporada {(career.seasonNumber ?? 1) + 1} →</button> : <button className="secondary" onClick={onCalendar}>Voltar ao calendário</button>}</section>
    {done && confirm && <section className="panel renewal-confirm" aria-labelledby="renew-title"><h3 id="renew-title">Iniciar a próxima temporada?</h3><p>Treinador, clube, escalação e evolução individual continuam. Treinos, entrosamento, desgaste e tabela atual reiniciam. Os resultados ficam no arquivo abaixo. Os clubes e o formato da liga são os mesmos nesta versão.</p><div className="renew-actions"><button className="secondary" onClick={() => setConfirm(false)}>Rever antes</button><button className="primary" onClick={() => { onChange(renewSeason(career)); setConfirm(false); onCalendar() }}>Confirmar nova temporada</button></div></section>}
    <section className="panel history-panel"><p className="eyebrow">ARQUIVO DA CARREIRA</p>{!career.archives?.length && <p className="muted">As temporadas encerradas aparecerão aqui ao iniciar a próxima.</p>}{career.archives?.map(a => { const rows = standings(a.results); const position = rows.findIndex(row => row.id === a.clubId) + 1; return <details className="season-archive" key={a.number}><summary><span>Temporada {a.number} · {clubs.find(c => c.id === a.clubId)?.name}</span><strong>{position}º lugar</strong></summary><p>Campeão: {rows[0].name} · Objetivo {position <= boardTarget(a.clubId) ? 'alcançado' : 'não alcançado'}.</p><div className="archive-table"><h3>Classificação final</h3>{rows.map((row, i) => <p key={row.id}><span>{i + 1}º · {row.name}</span><strong>{row.points} pts</strong></p>)}</div><h3>Evolução aplicada</h3><div className="player-ratings">{stats.filter(p => a.gains[p.id] > 0).map(p => <div key={p.id}><span>{p.name}</span><strong>+{a.gains[p.id]}</strong></div>)}</div><h3>Suas partidas</h3>{a.matches.map(h => { const home = h.match.events.filter(e => e.side === 'home' && e.goal).length; const away = h.match.events.filter(e => e.side === 'away' && e.goal).length; return <details className="history-result" key={h.day}><summary><span>Dia {h.day} · {h.day <= 7 ? 'Amistoso' : 'Liga'} · contra {clubs.find(c => c.id === h.match.opponent)?.name}</span><strong>{home} : {away}</strong></summary><p>Gols do seu time à esquerda · {h.match.formation} · força {h.match.strength}</p><div className="player-ratings">{h.match.ratings.map(r => <div key={r.playerId}><span>{stats.find(p => p.id === r.playerId)?.name}</span><strong>{r.value.toFixed(1)}</strong></div>)}</div></details> })}</details> })}</section>
  </section>
}
