import { useState } from 'react'
import { allPlayers, clubs, type Career } from './model'
import { acceptManagerOffer, ageOf, clubSquad, promoteProspect, worldOf } from './world'

const money = (value: number) => value >= 1000 ? `R$ ${(value / 1000).toFixed(1).replace('.', ',')} mi` : `R$ ${value} mil`
const clubName = (id?: string) => clubs.find(club => club.id === id)?.name ?? 'Sem clube'
export function WorldPanel({ career, onChange }: { career: Career; onChange: (career: Career) => void }) {
  const [offer, setOffer] = useState<string>()
  const [message, setMessage] = useState('')
  const world = worldOf(career)
  const prospects = world.prospects.map(id => allPlayers.find(player => player.id === id)!).filter(Boolean)
  const seasonTransfers = world.transfers.filter(item => item.season === (career.seasonNumber ?? 1))
  function promote(id: string, name: string) { const next = promoteProspect(career, id); if (next === career) return setMessage('O elenco está cheio ou uma partida está em andamento.'); onChange(next); setMessage(`${name} foi promovido e assinou por três temporadas.`) }
  return <section className="world-hub"><div className="world-hero"><div><p className="eyebrow">UNIVERSO VT27 · TEMPORADA {career.seasonNumber ?? 1}</p><h2>O futebol continua em movimento.</h2><p>Os outros clubes negociam, seus atletas envelhecem e uma nova geração pede espaço.</p></div><span aria-hidden="true">◎</span></div>
    <div className="season-stats world-numbers"><article><span>CLUBES ATIVOS</span><strong>{clubs.length}</strong></article><article><span>NEGÓCIOS DA TEMPORADA</span><strong>{seasonTransfers.length}</strong></article><article><span>APOSENTADORIAS</span><strong>{world.retirements.length}</strong></article><article><span>JOVENS OBSERVADOS</span><strong>{prospects.length}</strong></article></div>
    {message && <p className="market-message" role="status">{message}</p>}
    {!!world.managerOffers.length && <section className="panel job-market"><div className="section-heading"><div><p className="eyebrow">MERCADO DE TREINADORES</p><h2>Clubes interessados no seu trabalho</h2></div><span className="muted">Disponível durante a pré-temporada</span></div><div className="offer-grid">{world.managerOffers.map(id => { const club = clubs.find(item => item.id === id)!; return <article key={id}><span className="crest" style={{ color: club.color, borderColor: club.color }}>{club.initials}</span><div><h3>{club.name}</h3><p>{club.objective}</p></div><button className="secondary" onClick={() => setOffer(id)}>Ouvir proposta</button></article> })}</div>{offer && <div className="renewal-confirm"><h3>Assumir o {clubName(offer)}?</h3><p>Você passa a comandar o elenco e o orçamento do novo clube. Seu nome, temporadas anteriores, conquistas e histórico continuam na mesma carreira.</p><div className="renew-actions"><button className="secondary" onClick={() => setOffer(undefined)}>Permanecer no {clubName(career.clubId)}</button><button className="primary" onClick={() => { onChange(acceptManagerOffer(career, offer)); setMessage(`Você assumiu o ${clubName(offer)}.`); setOffer(undefined) }}>Aceitar proposta</button></div></div>}</section>}
    <section className="panel academy-panel"><div className="section-heading"><div><p className="eyebrow">CATEGORIAS DE BASE</p><h2>Nova geração</h2></div><span className="muted">Três observações renovadas por temporada</span></div>{prospects.length ? <div className="prospect-grid">{prospects.map(player => <article key={player.id}><div className="prospect-rating"><strong>{player.rating}</strong><span>{player.position}</span></div><h3>{player.name}</h3><p>{ageOf(career, player.id)} anos · salário R$ {player.wage} mil/mês</p><small>Valor inicial: {money(player.value)}</small><button className="primary" disabled={(career.roster?.length ?? 18) >= 23} onClick={() => promote(player.id, player.name)}>Promover ao profissional</button></article>)}</div> : <p className="muted">Todos os jovens observados nesta temporada já receberam uma decisão.</p>}<details className="rules-explainer"><summary>Como funciona a base?</summary><p>Os jovens são gerados pelo universo da carreira, têm nome, posição, idade, nível, salário e valor próprios. Ao promover, o atleta entra no elenco profissional com contrato de três temporadas. Uma nova lista chega no início de cada temporada.</p></details></section>
    <div className="world-columns"><section className="panel"><div className="section-heading"><h2>Mercado entre clubes</h2><span className="muted">Últimas movimentações</span></div>{!world.transfers.length ? <p className="muted">As primeiras movimentações acontecem na troca de temporada.</p> : <div className="world-feed">{world.transfers.slice(-12).reverse().map((item, index) => <article key={`${item.season}-${item.playerId}-${index}`}><span>T{item.season}</span><div><strong>{allPlayers.find(player => player.id === item.playerId)?.name}</strong><small>{clubName(item.fromClubId)} → {clubName(item.toClubId)}</small></div><b>{money(item.amount)}</b></article>)}</div>}</section>
      <section className="panel"><div className="section-heading"><h2>Aposentadorias</h2><span className="muted">Memória do universo</span></div>{!world.retirements.length ? <p className="muted">Nenhum atleta encerrou a carreira até agora.</p> : <div className="world-feed">{world.retirements.slice(-12).reverse().map(item => <article key={`${item.season}-${item.playerId}`}><span>T{item.season}</span><div><strong>{allPlayers.find(player => player.id === item.playerId)?.name}</strong><small>{clubName(item.clubId)} · aos {item.age} anos</small></div><b>APOSENTOU</b></article>)}</div>}</section></div>
    <section className="panel"><div className="section-heading"><div><p className="eyebrow">RAIO-X DA SÉRIE A</p><h2>Elencos do universo</h2></div><span className="muted">Atualizado depois de cada janela</span></div><div className="club-world-grid">{clubs.map(club => { const squad = clubSquad(career, club.id); const average = squad.length ? Math.round(squad.reduce((sum, player) => sum + player.rating, 0) / squad.length) : 0; return <article className={club.id === career.clubId ? 'managed' : ''} key={club.id}><span style={{ color: club.color }}>{club.initials}</span><div><strong>{club.name}</strong><small>{squad.length} atletas · nível médio {average}</small></div>{club.id === career.clubId && <b>SEU CLUBE</b>}</article> })}</div></section>
  </section>
}
